<!DOCTYPE html>
<html class="nojs html css_verticalspacer" lang="pt-BR">
 <head>
    <meta name="generator" content="2018.0.0.379"/>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" >
    <meta name="Description" content="<?php echo $mcs->st_title; ?>" />
    <meta name="<?php echo $mcs->st_autor; ?>" content="Portalget Inc">
  
<script type="text/javascript">
    // Update the 'nojs'/'js' class on the html node
    document.documentElement.className = document.documentElement.className.replace(/\bnojs\b/g, 'js');
    // Check that all required assets are uploaded and up-to-date
    if(typeof Muse == "undefined") window.Muse = {}; window.Muse.assets = {"required":["museutils.js", "museconfig.js", "jquery.watch.js", "require.js", "jquery.musepolyfill.bgsize.js", "webpro.js", "musewpslideshow.js", "jquery.museoverlay.js", "touchswipe.js", "jquery.scrolleffects.js", "login.css"], "outOfDate":[]};
</script>
  
  
  <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/site_global.css?crc=444006867"/>
  <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/master_page-login.css?crc=68217529"/>
  <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/login.css?crc=4239692135" id="pagesheet"/>
  <script src="https://portalget.com/src/scripts/html5shiv.js?crc=4241844378" type="text/javascript"></script>
  <link rel="shortcut icon" href="<?php echo $mcs->st_favicon; ?>" type="image/x-icon"/>
  <title><?php echo $mcs -> st_title; ?></title>
   </head>
 <body>

  <div class="clearfix" id="page"><!-- group -->
   <div class="clearfix grpelem" id="pslideshowu3473"><!-- group -->
    <div class="SlideShowWidget clearfix HeroFillFrame grpelem" id="slideshowu3473"><!-- none box -->
     <div class="popup_anchor" id="u3487popup">
      <div class="SlideShowContentPanel clearfix" id="u3487"><!-- stack box -->
       <div class="SSSlide clip_frame grpelem" id="u3488"><!-- image -->
        <img class="ImageInclude" id="u3488_img" data-src="https://portalget.com/src/images/cactus.jpg?crc=491424337" src="images/blank.gif?crc=4208392903" alt="" data-width="1160" data-height="870"/>
       </div>
       <div class="SSSlide invi clip_frame grpelem" id="u3492"><!-- image -->
        <img class="ImageInclude" id="u3492_img" data-src="https://portalget.com/src/images/road.jpg?crc=180693847" src="images/blank.gif?crc=4208392903" alt="" data-width="1160" data-height="870"/>
       </div>
       <div class="SSSlide invi clip_frame grpelem" id="u3490"><!-- image -->
        <img class="ImageInclude" id="u3490_img" data-src="https://portalget.com/src/images/trees.jpg?crc=4071309946" src="images/blank.gif?crc=4208392903" alt="" data-width="1160" data-height="870"/>
       </div>
      </div>
     </div>
    </div>
    <div class="gradient grpelem" id="u687"><!-- simple frame --></div>
    <div class="clearfix grpelem" id="u783-4"><!-- content -->
     <p id="u783-2">Registrar</p>
    </div>
    <div class="museBGSize grpelem" id="u810"><!-- simple frame --></div>
    <div class="clearfix grpelem" id="u823-4"><!-- content -->
     <p id="u823-2">Comece já, a sua atividade!</p>
    </div>
    <div class="museBGSize grpelem" id="u834"><!-- simple frame --></div>
    <div class="museBGSize grpelem" id="u837"><!-- simple frame --></div>
    <div class="clearfix grpelem" id="u3324-4"><!-- content -->
     <p>Nome Completo*</p>
    </div>
    <div class="clearfix grpelem" id="u3327-4"><!-- content -->
     <p>E-mail*</p>
    </div>
    <div class="clearfix grpelem" id="u3330-4"><!-- content -->
     <p>Utilizador*</p>
    </div>
	
<form action="/_tools/php/procss/signup.php" method="POST" >
	
    <div class="grpelem" id="u4790"><!-- custom html -->
     <input type="text" style="width:330px; 
height:30px; box-shadow: 0 0 3px #508ab2;
 margin:1px; font-size:12px; padding:0px 5px 0px 5px;" name="name" id="name_sig" ></input>
    </div>
    <div class="grpelem" id="u4795"><!-- custom html -->
     <input type="text" style="width:330px; 
height:30px; box-shadow: 0 0 3px #508ab2;
 margin:1px; font-size:12px; padding:0px 5px 0px 5px;" name="mail" id="email_sig" ></input>
    </div>
    <div class="grpelem" id="u4800"><!-- custom html -->
     <input type="text" style="width:330px; 
height:30px; box-shadow: 0 0 3px #508ab2;
 margin:1px; font-size:12px; padding:0px 5px 0px 5px;" name="user" id="user_sig" ></input>
    </div>
    <div class="grpelem" id="u4805"><!-- custom html -->
     <input type="submit" class="btn_seach_n2" value="Cadastre-se agora!" name="submit" ></input>
    </div>
</form>
	
    <div class="browser_width grpelem" id="u1183-bw">
     <div class="transition shadow" id="u1183"><!-- group -->
      <div class="clearfix" id="u1183_align_to_page">
       <div class="museBGSize grpelem" id="u1184"><!-- simple frame --></div>
	  
<form action="/_tools/php/procss/login.php" method="POST" >
       <div class="grpelem" id="u4775"><!-- custom html -->
        <input type="text" name="user" class="textFieldT_a" placeholder="Email ou Utilizador" ></input>
       </div>
       <div class="grpelem" id="u4780"><!-- custom html -->
        <input type="password" name="pass" class="textFieldT_b" placeholder="Senha" ></input>
       </div>
       <div class="grpelem" id="u4785"><!-- custom html -->
        <input type="submit" class="btn_seach_n1" value="Entrar" ></input>
       </div>
</form>
	   
       <div class="museBGSize grpelem" id="u1187"><!-- content --></div>
      </div>
     </div>
    </div>
    <div class="PamphletWidget clearfix grpelem" id="pamphletu11690"><!-- none box -->
     <div class="popup_anchor" id="u11693popup">
      <div class="ContainerGroup clearfix" id="u11693"><!-- stack box -->
       <div class="Container invi clearfix grpelem" id="u11694"><!-- column -->
        <div class="clearfix colelem" id="u11697-4"><!-- content -->
         <p>Ajuda?</p>
        </div>
        <div class="clearfix colelem" id="u11698-4"><!-- content -->
         <p>Esqueci a minha senha.</p>
        </div>
        <div class="clearfix colelem" id="u11699-4"><!-- content -->
         <p>Criar uma conta.</p>
        </div>
        <div class="clearfix colelem" id="u11695-4"><!-- content -->
         <p>Problemas com autenticação.</p>
        </div>
        <div class="clearfix colelem" id="u11696-4"><!-- content -->
         <p>Enviar relatório de erro.</p>
        </div>
       </div>
      </div>
     </div>
     <div class="ThumbGroup clearfix grpelem" id="u11704"><!-- none box -->
      <div class="popup_anchor" id="u11705popup">
       <div class="Thumb popup_element" id="u11705"><!-- simple frame --></div>
      </div>
     </div>
    </div>
   </div>
   <div class="PamphletWidget clearfix mse_pre_init" id="pamphletu24050"><!-- none box -->
    <div class="popup_anchor" id="u24059popup">
     <div class="ContainerGroup clearfix" id="u24059"><!-- stack box -->
      <div class="Container invi clearfix grpelem" id="u24060"><!-- column -->
       <div class="clearfix colelem" id="u24063-4"><!-- content -->
        <p>Ajuda?</p>
       </div>
       <div class="clearfix colelem" id="u24064-4"><!-- content -->
        <p>Esqueci a minha senha.</p>
       </div>
       <div class="clearfix colelem" id="u24065-4"><!-- content -->
        <p>Criar uma conta.</p>
       </div>
       <div class="clearfix colelem" id="u24061-4"><!-- content -->
        <p>Problemas com autenticação.</p>
       </div>
       <div class="clearfix colelem" id="u24062-4"><!-- content -->
        <p>Enviar relatório de erro.</p>
       </div>
      </div>
     </div>
    </div>
    <div class="ThumbGroup clearfix grpelem" id="u24057"><!-- none box -->
     <div class="popup_anchor" id="u24058popup">
      <div class="Thumb popup_element" id="u24058"><!-- simple frame --></div>
     </div>
    </div>
   </div>
   <div class="verticalspacer" data-offset-top="734" data-content-above-spacer="733" data-content-below-spacer="59"></div>
   <div class="clearfix grpelem" id="pu3221"><!-- group -->
    <div class="browser_width grpelem" id="u3221-bw">
     <div class="gradient" id="u3221"><!-- simple frame --></div>
    </div>
    <div class="browser_width grpelem" id="u3222-7-bw">
     <div class="clearfix" id="u3222-7"><!-- content -->
      <p id="u3222-2">Privacidade · Termos · Cookies · Português (Portugal) · mais</p>
      <p id="u3222-4">Copyright 2017 © Portalget, Inc.</p>
      <p>&nbsp;</p>
     </div>
    </div>
   </div>
  </div>
  <!-- Other scripts -->
<script type="text/javascript">
    setCookie('_mod', 'invalid_data' , 1, 'd');
    alert("ERTYUI");
   // Decide weather to suppress missing file error or not based on preference setting
var suppressMissingFileError = false
</script>
  <script type="text/javascript">
   window.Muse.assets.check=function(d){if(!window.Muse.assets.checked){window.Muse.assets.checked=!0;var b={},c=function(a,b){if(window.getComputedStyle){var c=window.getComputedStyle(a,null);return c&&c.getPropertyValue(b)||c&&c[b]||""}if(document.documentElement.currentStyle)return(c=a.currentStyle)&&c[b]||a.style&&a.style[b]||"";return""},a=function(a){if(a.match(/^rgb/))return a=a.replace(/\s+/g,"").match(/([\d\,]+)/gi)[0].split(","),(parseInt(a[0])<<16)+(parseInt(a[1])<<8)+parseInt(a[2]);if(a.match(/^\#/))return parseInt(a.substr(1),
16);return 0},g=function(g){for(var f=document.getElementsByTagName("link"),h=0;h<f.length;h++)if("text/css"==f[h].type){var i=(f[h].href||"").match(/\/?css\/([\w\-]+\.css)\?crc=(\d+)/);if(!i||!i[1]||!i[2])break;b[i[1]]=i[2]}f=document.createElement("div");f.className="version";f.style.cssText="display:none; width:1px; height:1px;";document.getElementsByTagName("body")[0].appendChild(f);for(h=0;h<Muse.assets.required.length;){var i=Muse.assets.required[h],l=i.match(/([\w\-\.]+)\.(\w+)$/),k=l&&l[1]?
l[1]:null,l=l&&l[2]?l[2]:null;switch(l.toLowerCase()){case "css":k=k.replace(/\W/gi,"_").replace(/^([^a-z])/gi,"_$1");f.className+=" "+k;k=a(c(f,"color"));l=a(c(f,"backgroundColor"));k!=0||l!=0?(Muse.assets.required.splice(h,1),"undefined"!=typeof b[i]&&(k!=b[i]>>>24||l!=(b[i]&16777215))&&Muse.assets.outOfDate.push(i)):h++;f.className="version";break;case "js":h++;break;default:throw Error("Unsupported file type: "+l);}}d?d().jquery!="1.8.3"&&Muse.assets.outOfDate.push("jquery-1.8.3.min.js"):Muse.assets.required.push("jquery-1.8.3.min.js");
f.parentNode.removeChild(f);if(Muse.assets.outOfDate.length||Muse.assets.required.length)f="Alguns arquivos no servidor podem estar ausentes ou incorretos. Limpe o cache do navegador e tente novamente. Se o problema persistir, entre em contato com o autor do site.",g&&Muse.assets.outOfDate.length&&(f+="\nOut of date: "+Muse.assets.outOfDate.join(",")),g&&Muse.assets.required.length&&(f+="\nMissing: "+Muse.assets.required.join(",")),suppressMissingFileError?(f+="\nUse SuppressMissingFileError key in AppPrefs.xml to show missing file error pop up.",console.log(f)):f};location&&location.search&&location.search.match&&location.search.match(/muse_debug/gi)?
setTimeout(function(){g(!0)},5E3):g()}};
var muse_init=function(){require.config({baseUrl:"https://portalget.com/src/"});require(["jquery","museutils","whatinput","webpro","musewpslideshow","jquery.museoverlay","touchswipe","jquery.musepolyfill.bgsize","jquery.watch","jquery.scrolleffects"],function(d){var $ = d;$(document).ready(function(){try{
window.Muse.assets.check($);/* body */
Muse.Utils.transformMarkupToFixBrowserProblemsPreInit();/* body */
Muse.Utils.prepHyperlinks(true);/* body */
Muse.Utils.resizeHeight('.browser_width');/* resize height */
Muse.Utils.requestAnimationFrame(function() { $('body').addClass('initialized'); });/* mark body as initialized */
Muse.Utils.makeButtonsVisibleAfterSettingMinWidth();/* body */
Muse.Utils.initWidget('#slideshowu3473', ['#bp_infinity'], function(elem) { var widget = new WebPro.Widget.ContentSlideShow(elem, {autoPlay:true,displayInterval:3500,slideLinkStopsSlideShow:false,transitionStyle:'fading',lightboxEnabled_runtime:false,shuffle:false,transitionDuration:500,enableSwipe:true,elastic:'fullWidth',resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); $(elem).data('widget', widget); return widget; });/* #slideshowu3473 */
Muse.Utils.initWidget('#pamphletu11690', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_click',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:500,hideAllContentsFirst:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu11690 */
Muse.Utils.initWidget('#pamphletu24050', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_click',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:500,hideAllContentsFirst:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu24050 */
Muse.Utils.fullPage('#page');/* 100% height page */
$('#pamphletu24050').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,0]},{"speed":[0,0],"in":[0,Infinity]}]);/* scroll effect */
Muse.Utils.showWidgetsWhenReady();/* body */
Muse.Utils.transformMarkupToFixBrowserProblems();/* body */
}catch(b){if(b&&"function"==typeof b.notify?b.notify():Muse.Assert.fail("Error calling selector function: "+b),false)throw b;}})})};

</script>
  <!-- RequireJS script -->
  <script src="https://portalget.com/src/scripts/require.js?crc=4157109226" type="text/javascript" async data-main="https://portalget.com/src/scripts/museconfig.js?crc=4153641093" onload="if (requirejs) requirejs.onError = function(requireType, requireModule) { if (requireType && requireType.toString && requireType.toString().indexOf && 0 <= requireType.toString().indexOf('#scripterror')) window.Muse.assets.check(); }" onerror="window.Muse.assets.check();"></script>
   </body>
</html>

<style>
.btn_seach_n1 {
  background: #508ab2;
  background-image: -webkit-linear-gradient(top, #508ab2, #2980b9);
  background-image: -moz-linear-gradient(top, #508ab2, #2980b9);
  background-image: -ms-linear-gradient(top, #508ab2, #2980b9);
  background-image: -o-linear-gradient(top, #508ab2, #2980b9);
  background-image: linear-gradient(to bottom, #508ab2, #2980b9);
  text-shadow: 1px 1px 3px #666666;
  -webkit-box-shadow: 0px 1px 3px #666666;
  -moz-box-shadow: 0px 1px 3px #666666;
  box-shadow: 0px 1px 3px #666666;
  font-family: Arial;
  color: #ffffff;
  font-size: 14px;
  padding: 5px 10px;
  background: #508ab2;
  text-decoration: none;
  cursor:pointer;
}
.btn_seach_n2 {
  background: #002148;
  background-image: -webkit-linear-gradient(top, #002148, #2980b9);
  background-image: -moz-linear-gradient(top, #002148, #2980b9);
  background-image: -ms-linear-gradient(top, #002148, #2980b9);
  background-image: -o-linear-gradient(top, #002148, #2980b9);
  background-image: linear-gradient(to bottom, #002148, #2980b9);
  text-shadow: 1px 1px 3px #666666;
  -webkit-box-shadow: 0px 1px 3px #666666;
  -moz-box-shadow: 0px 1px 3px #666666;
  box-shadow: 0px 1px 3px #666666;
  font-family: Arial;
  color: #ffffff;
  font-size: 14px;
  padding: 10px 110px;
  background: #002148;
  text-decoration: none;
  cursor:pointer;
}
.textFieldT_a{
	width:150px; 
	height:25px; box-shadow: 0 0 3px #508ab2;
	margin:1px; font-size:12px; padding:0px 5px 0px 5px;
}
.textFieldT_b{
	width:145px; 
	height:25px; box-shadow: 0 0 3px #508ab2;
	margin:1px; font-size:12px; padding:0px 5px 0px 5px;
}
</style>

<script>
$("#name_sig").text('');
$("#email_sig").text('');
$("#user_sig").text('');
</script>