<!DOCTYPE html>
<html class="nojs html css_verticalspacer" lang="pt-BR">
 <head>

  <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>
  <meta name="generator" content="2018.1.0.386"/>
  
  <script type="text/javascript">
   // Redirect to phone/tablet as necessary
(function(c,b,d){var a=function(){if(navigator.maxTouchPoints>1)return!0;if(window.matchMedia&&window.matchMedia("(-moz-touch-enabled)").matches)return!0;for(var a=["Webkit","Moz","O","ms","Khtml"],b=0,c=a.length;b<c;b++){var d=a[b]+"MaxTouchPoints";if(d in navigator&&navigator[d])return!0}try{return document.createEvent("TouchEvent"),!0}catch(f){}return!1}(),f=function(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];d.charAt(0)==" ";)d=d.substring(1,d.length);if(d.indexOf(a)==
0)return d.substring(a.length,d.length)}return null};if(f("inbrowserediting")!="true"){var h,f=f("devicelock");f=="phone"&&d?h=d:f=="tablet"&&b&&(h=b);if(f!=c&&!h)if(window.matchMedia)window.matchMedia("(max-device-width: 415px)").matches&&d?h=d:window.matchMedia("(max-device-width: 960px)").matches&&b&&a&&(h=b);else{var c=Math.min(screen.width,screen.height)/(window.devicePixelRatio||1),f=window.screen.systemXDPI||0,g=window.screen.systemYDPI||0,f=f>0&&g>0?Math.min(screen.width/f,screen.height/g):
0;(c<=370||f!=0&&f<=3)&&d?h=d:c<=960&&b&&a&&(h=b)}if(h)document.location=h+(document.location.search||"")+(document.location.hash||""),document.write('<style type="text/css">body {visibility:hidden}</style>')}})("desktop","","phone/searchvisite.html");

// Update the 'nojs'/'js' class on the html node
document.documentElement.className = document.documentElement.className.replace(/\bnojs\b/g, 'js');

// Check that all required assets are uploaded and up-to-date
if(typeof Muse == "undefined") window.Muse = {}; window.Muse.assets = {"required":["museutils.js", "museconfig.js", "jquery.watch.js", "require.js", "jquery.musepolyfill.bgsize.js", "webpro.js", "musewpslideshow.js", "jquery.museoverlay.js", "touchswipe.js", "jquery.scrolleffects.js", "searchvisite.css"], "outOfDate":[]};
</script>
  
  <link media="only screen and (max-width: 370px)" rel="alternate" href="https://www.portalget.com/phone/searchvisite.html"/>
  <title>searchvisite</title>
  <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/site_global.css?crc=444006867"/>
  <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/master_page-visite03.css?crc=259135123"/>
  <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/searchvisite.css?crc=4104003317" id="pagesheet"/>
  <!-- JS includes -->
  <!--[if lt IE 9]>
  <script src="scripts/html5shiv.js?crc=4241844378" type="text/javascript"></script>
  <![endif]-->
   </head>
 <body>

  <div class="clearfix" id="page"><!-- group -->
   <div class="clearfix grpelem" id="pu18627"><!-- group -->
    <div class="browser_width" id="u18627-bw">
     <div class="shadow" id="u18627"><!-- simple frame --></div>
    </div>
    <div class="browser_width mse_pre_init" id="u18575-bw">
     <div id="u18575"><!-- simple frame --></div>
    </div>
    <div class="clearfix mse_pre_init" id="u18576-4"><!-- content -->
     <p>Todos</p>
    </div>
    <div class="clearfix mse_pre_init" id="u18577-4"><!-- content -->
     <p>Imagens</p>
    </div>
    <div class="clearfix mse_pre_init" id="u18578-4"><!-- content -->
     <p>Documentos</p>
    </div>
    <div class="clearfix mse_pre_init" id="u18579-4"><!-- content -->
     <p>Mais</p>
    </div>
    <div class="browser_width" id="u23975-bw">
     <div id="u23975"><!-- simple frame --></div>
    </div>
    <div class="museBGSize" id="u18580"><!-- simple frame --></div>
    <div class="mse_pre_init" id="u18581"><!-- custom html -->
     <input type="text" style="width:510px; 
height:30px; box-shadow: 0 0 3px #508ab2;
 margin:1px; font-size:14px; padding:0px 35px 0px 10px;" ></input>
    </div>
    <div class="museBGSize mse_pre_init" id="u18582"><!-- simple frame --></div>
   </div>
   <div class="clearfix grpelem" id="pu18573-4"><!-- column -->
    <div class="clearfix colelem" id="u18573-4"><!-- content -->
     <p>Cerca de 18 200 000 resultados (0,58 segundos)</p>
    </div>
    <div class="clearfix colelem" id="u18570-4"><!-- content -->
     <p>Lorem issupum dolore Lorem issupum dolore Lorem issupum Lorem issupum</p>
    </div>
    <div class="clearfix colelem" id="u18572-4"><!-- content -->
     <p>http://Lorem issupum doloreLorem issupum dolore Lorem issupum dolore .com</p>
    </div>
    <div class="clearfix colelem" id="u18571-4"><!-- content -->
     <p>Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum .....</p>
    </div>
    <div class="clearfix colelem" id="u18562-4"><!-- content -->
     <p>Lorem issupum dolore Lorem issupum dolore Lorem issupum Lorem issupum</p>
    </div>
    <div class="clearfix colelem" id="u18564-4"><!-- content -->
     <p>http://Lorem issupum doloreLorem issupum dolore Lorem issupum dolore .com</p>
    </div>
    <div class="clearfix colelem" id="u18563-4"><!-- content -->
     <p>Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum .....</p>
    </div>
    <div class="clearfix colelem" id="u18565-4"><!-- content -->
     <p>Lorem issupum dolore Lorem issupum dolore Lorem issupum Lorem issupum</p>
    </div>
    <div class="clearfix colelem" id="u18567-4"><!-- content -->
     <p>http://Lorem issupum doloreLorem issupum dolore Lorem issupum dolore .com</p>
    </div>
    <div class="clearfix colelem" id="u18566-4"><!-- content -->
     <p>Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum dolore Lorem issupum .....</p>
    </div>
    <div class="museBGSize colelem" id="u18568"><!-- simple frame --></div>
    <div class="clearfix colelem" id="u18569-4"><!-- content -->
     <p><span id="u18569">Fim de resultado</span></p>
    </div>
   </div>
   <div class="grpelem" id="u18574"><!-- simple frame --></div>
   <div class="clearfix grpelem" id="pu23994"><!-- group -->
    <div class="mse_pre_init" id="u23994"><!-- content --></div>
    <div class="mse_pre_init" id="u23995"><!-- custom html -->
     <button type="button" style="
 background: #508ab2;
  background-image: -webkit-linear-gradient(top, #508ab2, #2980b9);
  background-image: -moz-linear-gradient(top, #508ab2, #2980b9);
  background-image: -ms-linear-gradient(top, #508ab2, #2980b9);
  background-image: -o-linear-gradient(top, #508ab2, #2980b9);
  background-image: linear-gradient(to bottom, #508ab2, #2980b9);
  text-shadow: 1px 1px 3px #666666;
  -webkit-box-shadow: 0px 1px 3px #666666;
  -moz-box-shadow: 0px 1px 3px #666666;
  box-shadow: 0px 1px 3px #666666;
  font-family: Arial;
  color: #ffffff;
  font-size: 14px;
  padding: 5px 10px;
  background: #508ab2;
  text-decoration: none;
" >Entrar</button>

    </div>
    <div class="PamphletWidget clearfix mse_pre_init" id="pamphletu24002"><!-- none box -->
     <div class="popup_anchor" id="u24011popup">
      <div class="ContainerGroup clearfix" id="u24011"><!-- stack box -->
       <div class="Container invi clearfix grpelem" id="u24012"><!-- column -->
        <div class="clearfix colelem" id="u24015-4"><!-- content -->
         <p>Ajuda?</p>
        </div>
        <div class="clearfix colelem" id="u24016-4"><!-- content -->
         <p>Esqueci a minha senha.</p>
        </div>
        <div class="clearfix colelem" id="u24017-4"><!-- content -->
         <p>Criar uma conta.</p>
        </div>
        <div class="clearfix colelem" id="u24013-4"><!-- content -->
         <p>Problemas com autenticação.</p>
        </div>
        <div class="clearfix colelem" id="u24014-4"><!-- content -->
         <p>Enviar relatório de erro.</p>
        </div>
       </div>
      </div>
     </div>
     <div class="ThumbGroup clearfix grpelem" id="u24009"><!-- none box -->
      <div class="popup_anchor" id="u24010popup">
       <div class="Thumb popup_element" id="u24010"><!-- simple frame --></div>
      </div>
     </div>
    </div>
   </div>
   <div class="verticalspacer" data-offset-top="614" data-content-above-spacer="613" data-content-below-spacer="71"></div>
   <div class="browser_width grpelem" id="u23973-bw">
    <div id="u23973"><!-- group -->
     <div class="clearfix" id="u23973_align_to_page">
      <div class="clearfix grpelem" id="u23974-6"><!-- content -->
       <p>Privacidade · Termos · Cookies · Português (Portugal) · mais</p>
       <p>Copyright 2017 © Portalget, Inc.</p>
      </div>
     </div>
    </div>
   </div>
  </div>
  <!-- Other scripts -->
  <script type="text/javascript">
   // Decide whether to suppress missing file error or not based on preference setting
var suppressMissingFileError = false
</script>
  <script type="text/javascript">
   window.Muse.assets.check=function(c){if(!window.Muse.assets.checked){window.Muse.assets.checked=!0;var b={},d=function(a,b){if(window.getComputedStyle){var c=window.getComputedStyle(a,null);return c&&c.getPropertyValue(b)||c&&c[b]||""}if(document.documentElement.currentStyle)return(c=a.currentStyle)&&c[b]||a.style&&a.style[b]||"";return""},a=function(a){if(a.match(/^rgb/))return a=a.replace(/\s+/g,"").match(/([\d\,]+)/gi)[0].split(","),(parseInt(a[0])<<16)+(parseInt(a[1])<<8)+parseInt(a[2]);if(a.match(/^\#/))return parseInt(a.substr(1),
16);return 0},f=function(f){for(var g=document.getElementsByTagName("link"),j=0;j<g.length;j++)if("text/css"==g[j].type){var l=(g[j].href||"").match(/\/?css\/([\w\-]+\.css)\?crc=(\d+)/);if(!l||!l[1]||!l[2])break;b[l[1]]=l[2]}g=document.createElement("div");g.className="version";g.style.cssText="display:none; width:1px; height:1px;";document.getElementsByTagName("body")[0].appendChild(g);for(j=0;j<Muse.assets.required.length;){var l=Muse.assets.required[j],k=l.match(/([\w\-\.]+)\.(\w+)$/),i=k&&k[1]?
k[1]:null,k=k&&k[2]?k[2]:null;switch(k.toLowerCase()){case "css":i=i.replace(/\W/gi,"_").replace(/^([^a-z])/gi,"_$1");g.className+=" "+i;i=a(d(g,"color"));k=a(d(g,"backgroundColor"));i!=0||k!=0?(Muse.assets.required.splice(j,1),"undefined"!=typeof b[l]&&(i!=b[l]>>>24||k!=(b[l]&16777215))&&Muse.assets.outOfDate.push(l)):j++;g.className="version";break;case "js":j++;break;default:throw Error("Unsupported file type: "+k);}}c?c().jquery!="1.8.3"&&Muse.assets.outOfDate.push("jquery-1.8.3.min.js"):Muse.assets.required.push("jquery-1.8.3.min.js");
g.parentNode.removeChild(g);if(Muse.assets.outOfDate.length||Muse.assets.required.length)g="Alguns arquivos no servidor podem estar ausentes ou incorretos. Limpe o cache do navegador e tente novamente. Se o problema persistir, entre em contato com o autor do site.",f&&Muse.assets.outOfDate.length&&(g+="\nOut of date: "+Muse.assets.outOfDate.join(",")),f&&Muse.assets.required.length&&(g+="\nMissing: "+Muse.assets.required.join(",")),suppressMissingFileError?(g+="\nUse SuppressMissingFileError key in AppPrefs.xml to show missing file error pop up.",console.log(g)):g};location&&location.search&&location.search.match&&location.search.match(/muse_debug/gi)?
setTimeout(function(){f(!0)},5E3):f()}};
var muse_init=function(){require.config({baseUrl:"https://portalget.com/src/"});require(["jquery","museutils","whatinput","jquery.watch","jquery.musepolyfill.bgsize","webpro","musewpslideshow","jquery.museoverlay","touchswipe","jquery.scrolleffects"],function(c){var $ = c;$(document).ready(function(){try{
window.Muse.assets.check($);/* body */
Muse.Utils.transformMarkupToFixBrowserProblemsPreInit();/* body */
Muse.Utils.prepHyperlinks(true);/* body */
Muse.Utils.resizeHeight('.browser_width');/* resize height */
Muse.Utils.requestAnimationFrame(function() { $('body').addClass('initialized'); });/* mark body as initialized */
Muse.Utils.makeButtonsVisibleAfterSettingMinWidth();/* body */
Muse.Utils.initWidget('#pamphletu24002', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_click',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:500,hideAllContentsFirst:true,triggersOnTop:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu24002 */
Muse.Utils.fullPage('#page');/* 100% height page */
$('#u18575-bw').registerPositionScrollEffect([{"in":[-Infinity,-2],"speed":[null,1]},{"in":[-2,Infinity],"speed":[null,0]}]);/* scroll effect */
$('#u18576-4').registerPositionScrollEffect([{"in":[-Infinity,-2],"speed":[1,1]},{"in":[-2,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u18577-4').registerPositionScrollEffect([{"in":[-Infinity,-2],"speed":[1,1]},{"in":[-2,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u18578-4').registerPositionScrollEffect([{"in":[-Infinity,-2],"speed":[1,1]},{"in":[-2,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u18579-4').registerPositionScrollEffect([{"in":[-Infinity,-2],"speed":[1,1]},{"in":[-2,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u18581').registerPositionScrollEffect([{"in":[-Infinity,-2],"speed":[1,1]},{"in":[-2,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u18582').registerPositionScrollEffect([{"in":[-Infinity,-2],"speed":[1,1]},{"in":[-2,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u23994').registerPositionScrollEffect([{"in":[-Infinity,0],"speed":[1,1]},{"in":[0,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u23995').registerPositionScrollEffect([{"in":[-Infinity,0],"speed":[0,1]},{"in":[0,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#pamphletu24002').registerPositionScrollEffect([{"in":[-Infinity,0],"speed":[0,1]},{"in":[0,Infinity],"speed":[0,0]}]);/* scroll effect */
Muse.Utils.showWidgetsWhenReady();/* body */
Muse.Utils.transformMarkupToFixBrowserProblems();/* body */
}catch(b){if(b&&"function"==typeof b.notify?b.notify():Muse.Assert.fail("Error calling selector function: "+b),false)throw b;}})})};

</script>
  <!-- RequireJS script -->
  <script src="https://portalget.com/src/scripts/require.js?crc=7928878" type="text/javascript" async data-main="https://portalget.com/src/scripts/museconfig.js?crc=310584261" onload="if (requirejs) requirejs.onError = function(requireType, requireModule) { if (requireType && requireType.toString && requireType.toString().indexOf && 0 <= requireType.toString().indexOf('#scripterror')) window.Muse.assets.check(); }" onerror="window.Muse.assets.check();"></script>
   </body>
</html>
