<!DOCTYPE html>
<html class="nojs html css_verticalspacer" lang="pt-BR">
 <head>

  <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>
  <meta name="generator" content="2018.1.0.386"/>
  
  <script type="text/javascript">
   // Update the 'nojs'/'js' class on the html node
document.documentElement.className = document.documentElement.className.replace(/\bnojs\b/g, 'js');

// Check that all required assets are uploaded and up-to-date
if(typeof Muse == "undefined") window.Muse = {}; window.Muse.assets = {"required":["museutils.js", "museconfig.js", "jquery.watch.js", "require.js", "jquery.musepolyfill.bgsize.js", "webpro.js", "musewpslideshow.js", "jquery.museoverlay.js", "touchswipe.js", "jquery.musemenu.js", "jquery.scrolleffects.js", "profile.css"], "outOfDate":[]};
</script>
  
  <title>profile</title>
  <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/site_global.css?crc=444006867"/>
  <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/profile.css?crc=3839481416" id="pagesheet"/>
  <!-- JS includes -->
  <!--[if lt IE 9]>
  <script src="scripts/html5shiv.js?crc=4241844378" type="text/javascript"></script>
  <![endif]-->
   </head>
 <body>

  <div class="clearfix" id="page"><!-- group -->
   <div class="clearfix grpelem" id="pu2856"><!-- group -->
    <div class="browser_width mse_pre_init" id="u2856-bw">
     <div class="transition shadow" id="u2856"><!-- simple frame --></div>
    </div>
    <div class="museBGSize mse_pre_init" id="u2865"><!-- simple frame --></div>
    <div class="mse_pre_init" id="u4977"><!-- simple frame --></div>
    <div class="museBGSize rounded-corners mse_pre_init" id="u7973"><!-- simple frame --></div>
    <div class="museBGSize mse_pre_init" id="u7974"><!-- simple frame --></div>
    <div class="shadow rounded-corners mse_pre_init" id="u7975"><!-- simple frame --></div>
    <div class="clearfix mse_pre_init" id="u7976-4"><!-- content -->
     <p id="u7976-2">5</p>
    </div>
    <div class="museBGSize mse_pre_init" id="u8595"><!-- simple frame --></div>
    <div class="PamphletWidget clearfix mse_pre_init" id="pamphletu25510"><!-- none box -->
     <div class="popup_anchor" id="u25513popup">
      <div class="ContainerGroup clearfix" id="u25513"><!-- stack box -->
       <div class="Container invi rounded-corners clearfix grpelem" id="u25514"><!-- column -->
        <div class="clearfix colelem" id="pu25554"><!-- group -->
         <div class="grpelem" id="u25554"><!-- simple frame --></div>
         <div class="museBGSize rounded-corners grpelem" id="u25556"><!-- simple frame --></div>
         <div class="clearfix grpelem" id="u25515-4"><!-- content -->
          <p>agostinhopina95@gmail.com</p>
         </div>
         <div class="clearfix grpelem" id="u25552-4"><!-- content -->
          <p>Agostinho De Pina Ramos</p>
         </div>
        </div>
        <div class="clearfix colelem" id="u25555"><!-- column -->
         <nav class="MenuBar clearfix colelem" id="menuu25516"><!-- vertical box -->
          <div class="MenuItemContainer clearfix colelem" id="u25524"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u25527"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u25530"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u25528-4"><!-- content -->
             <p>Ver o meu perfil</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u25538"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u25541"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u25542"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u25544-4"><!-- content -->
             <p>Editor Online</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u25531"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u25532"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u25535"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u25533-4"><!-- content -->
             <p>Criar uma etiqueta</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u25545"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u25548"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u25551"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u25550-4"><!-- content -->
             <p>Criar um grupo</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u25517"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u25520"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u25521"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u25523-4"><!-- content -->
             <p>Ver questões</p>
            </div>
           </div>
          </div>
         </nav>
         <div class="colelem" id="u25553"><!-- simple frame --></div>
         <nav class="MenuBar clearfix colelem" id="menuu25557"><!-- vertical box -->
          <div class="MenuItemContainer clearfix colelem" id="u25565"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u25566"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u25569"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u25568-4"><!-- content -->
             <p>Definições</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u25558"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u25561"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u25563"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u25562-4"><!-- content -->
             <p>Terminar sessão</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u25572"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u25575"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u25576"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u25577-4"><!-- content -->
             <p>Ajuda</p>
            </div>
           </div>
          </div>
         </nav>
        </div>
       </div>
      </div>
     </div>
     <div class="ThumbGroup clearfix grpelem" id="u25511"><!-- none box -->
      <div class="popup_anchor" id="u25512popup">
       <div class="Thumb popup_element" id="u25512"><!-- simple frame --></div>
      </div>
     </div>
    </div>
    <div class="PamphletWidget clearfix mse_pre_init" id="pamphletu25642"><!-- none box -->
     <div class="popup_anchor" id="u25645popup">
      <div class="ContainerGroup clearfix" id="u25645"><!-- stack box -->
       <div class="Container invi rounded-corners clearfix grpelem" id="u25646"><!-- column -->
        <div class="clearfix colelem" id="pu25653"><!-- group -->
         <div class="rounded-corners grpelem" id="u25653"><!-- simple frame --></div>
         <div class="grpelem" id="u25648"><!-- simple frame --></div>
         <div class="museBGSize rounded-corners grpelem" id="u25663"><!-- content --></div>
         <div class="clearfix grpelem" id="u25665-6"><!-- content -->
          <p><span id="u25665">Agostinho de Pina Ramos</span> publicou em etiqueta <span id="u25665-3">Java.</span></p>
         </div>
         <div class="clearfix grpelem" id="u25661-4"><!-- content -->
          <p>Ontem ás 16h00</p>
         </div>
         <div class="museBGSize grpelem" id="u25664"><!-- simple frame --></div>
         <div class="grpelem" id="u25659"><!-- simple frame --></div>
         <div class="grpelem" id="u25654"><!-- simple frame --></div>
         <div class="museBGSize rounded-corners grpelem" id="u25658"><!-- content --></div>
         <div class="clearfix grpelem" id="u25649-6"><!-- content -->
          <p><span id="u25649">Agostinho de Pina Ramos</span> publicou em etiqueta <span id="u25649-3">Java.</span></p>
         </div>
         <div class="clearfix grpelem" id="u25650-4"><!-- content -->
          <p>Ontem ás 16h00</p>
         </div>
         <div class="museBGSize grpelem" id="u25647"><!-- simple frame --></div>
         <div class="grpelem" id="u25657"><!-- simple frame --></div>
         <div class="PamphletWidget clearfix grpelem" id="pamphletu25666"><!-- none box -->
          <div class="popup_anchor" id="u25673popup">
           <div class="ContainerGroup clearfix" id="u25673"><!-- stack box -->
            <div class="Container invi clearfix grpelem" id="u25674"><!-- group -->
             <div class="clearfix grpelem" id="pu25675"><!-- column -->
              <div class="colelem" id="u25675"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
              <div class="colelem" id="u25682"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
              <div class="colelem" id="u25676"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
              <div class="colelem" id="u25677"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
             </div>
             <div class="clearfix grpelem" id="pu25679-4"><!-- column -->
              <div class="clearfix colelem" id="u25679-4"><!-- content -->
               <p>Alert icon</p>
              </div>
              <div class="clearfix colelem" id="u25681-4"><!-- content -->
               <p>Alert song</p>
              </div>
              <div class="clearfix colelem" id="u25678-4"><!-- content -->
               <p>Auto refresh</p>
              </div>
              <div class="clearfix colelem" id="u25680-4"><!-- content -->
               <p>Desativar</p>
              </div>
             </div>
            </div>
           </div>
          </div>
          <div class="ThumbGroup clearfix grpelem" id="u25671"><!-- none box -->
           <div class="popup_anchor" id="u25672popup">
            <div class="Thumb popup_element museBGSize" id="u25672"><!-- simple frame --></div>
           </div>
          </div>
         </div>
         <div class="clearfix grpelem" id="u25685-4"><!-- content -->
          <p>Notificações</p>
         </div>
        </div>
        <div class="clearfix colelem" id="pu25651"><!-- group -->
         <div class="grpelem" id="u25651"><!-- simple frame --></div>
         <div class="museBGSize rounded-corners grpelem" id="u25656"><!-- content --></div>
         <div class="clearfix grpelem" id="u25662-6"><!-- content -->
          <p><span id="u25662">Agostinho de Pina Ramos</span> publicou em etiqueta <span id="u25662-3">Java.</span></p>
         </div>
         <div class="clearfix grpelem" id="u25660-4"><!-- content -->
          <p>Ontem ás 16h00</p>
         </div>
         <div class="museBGSize grpelem" id="u25652"><!-- simple frame --></div>
         <div class="grpelem" id="u25655"><!-- simple frame --></div>
        </div>
       </div>
      </div>
     </div>
     <div class="ThumbGroup clearfix grpelem" id="u25690"><!-- none box -->
      <div class="popup_anchor" id="u25691popup">
       <div class="Thumb popup_element" id="u25691"><!-- simple frame --></div>
      </div>
     </div>
    </div>
   </div>
   <div class="clearfix grpelem" id="ppu4464"><!-- column -->
    <div class="clearfix colelem" id="pu4464"><!-- group -->
     <div class="browser_width grpelem" id="u4464-bw">
      <div class="gradient" id="u4464"><!-- group -->
       <div class="clearfix" id="u4464_align_to_page">
        <div class="grpelem" id="u4972"><!-- custom html -->
         <button type="button" style="
 background: #508ab2;
  background-image: -webkit-linear-gradient(top, #508ab2, #2980b9);
  background-image: -moz-linear-gradient(top, #508ab2, #2980b9);
  background-image: -ms-linear-gradient(top, #508ab2, #2980b9);
  background-image: -o-linear-gradient(top, #508ab2, #2980b9);
  background-image: linear-gradient(to bottom, #508ab2, #2980b9);
  text-shadow: 1px 1px 3px #666666;
  -webkit-box-shadow: 0px 1px 3px #666666;
  -moz-box-shadow: 0px 1px 3px #666666;
  box-shadow: 0px 1px 3px #666666;
  font-family: Arial;
  color: #ffffff;
  font-size: 14px;
  padding: 5px 10px;
  background: #508ab2;
  text-decoration: none;
" >Iniciar uma conversa</button>

        </div>
        <div class="clearfix grpelem" id="ppu4915"><!-- column -->
         <div class="clearfix colelem" id="pu4915"><!-- group -->
          <div class="museBGSize clearfix grpelem" id="u4915"><!-- group -->
           <div class="museBGSize grpelem" id="u4934"><!-- simple frame --></div>
          </div>
          <div class="PamphletWidget clearfix grpelem" id="pamphletu10618"><!-- none box -->
           <div class="popup_anchor" id="u10623popup">
            <div class="ContainerGroup clearfix" id="u10623"><!-- stack box -->
             <div class="Container invi clearfix grpelem" id="u10624"><!-- group -->
              <div class="clearfix grpelem" id="pu10626"><!-- column -->
               <div class="colelem" id="u10626"><!-- custom html -->
                <input type="checkbox" value="" >
               </div>
               <div class="colelem" id="u10631"><!-- custom html -->
                <input type="checkbox" value="">
               </div>
               <div class="colelem" id="u10629"><!-- custom html -->
                <input type="checkbox" value="" >
               </div>
               <div class="colelem" id="u10628"><!-- custom html -->
                <input type="checkbox" value="" >
               </div>
              </div>
              <div class="clearfix grpelem" id="pu10630-4"><!-- column -->
               <div class="clearfix colelem" id="u10630-4"><!-- content -->
                <p>Alert icon</p>
               </div>
               <div class="clearfix colelem" id="u10632-4"><!-- content -->
                <p>Alert song</p>
               </div>
               <div class="clearfix colelem" id="u10625-4"><!-- content -->
                <p>Auto refresh</p>
               </div>
               <div class="clearfix colelem" id="u10627-4"><!-- content -->
                <p>Desativar</p>
               </div>
              </div>
             </div>
            </div>
           </div>
           <div class="ThumbGroup clearfix grpelem" id="u10635"><!-- none box -->
            <div class="popup_anchor" id="u10636popup">
             <div class="Thumb popup_element" id="u10636"><!-- simple frame --></div>
            </div>
           </div>
          </div>
         </div>
         <div class="clearfix colelem" id="pu4442-4"><!-- group -->
          <div class="clearfix grpelem" id="u4442-4"><!-- content -->
           <p id="u4442-2">Agostinho Pina De Ramos</p>
          </div>
          <div class="museBGSize grpelem" id="u4931"><!-- simple frame --></div>
         </div>
        </div>
       </div>
      </div>
     </div>
     <div class="grpelem" id="u4958"><!-- custom html -->
      <button type="button" style="
 background: #508ab2;
  background-image: -webkit-linear-gradient(top, #508ab2, #2980b9);
  background-image: -moz-linear-gradient(top, #508ab2, #2980b9);
  background-image: -ms-linear-gradient(top, #508ab2, #2980b9);
  background-image: -o-linear-gradient(top, #508ab2, #2980b9);
  background-image: linear-gradient(to bottom, #508ab2, #2980b9);
  text-shadow: 1px 1px 3px #666666;
  -webkit-box-shadow: 0px 1px 3px #666666;
  -moz-box-shadow: 0px 1px 3px #666666;
  box-shadow: 0px 1px 3px #666666;
  font-family: Arial;
  color: #ffffff;
  font-size: 14px;
  padding: 5px 10px;
  background: #508ab2;
  text-decoration: none;
" >Ajuntar</button>

     </div>
    </div>
    <div class="clearfix colelem" id="pppu4446"><!-- group -->
     <div class="clearfix grpelem" id="ppu4446"><!-- column -->
      <div class="clearfix colelem" id="pu4446"><!-- group -->
       <div class="grpelem" id="u4446"><!-- simple frame --></div>
       <div class="clearfix grpelem" id="u4449-5"><!-- content -->
        <p id="u4449-3"><span id="u4449">Estuda em </span><span id="u4449-2">Sua Escola Oficial</span></p>
       </div>
       <div class="clearfix grpelem" id="u4452-9"><!-- content -->
        <p id="u4452-3"><span id="u4452">Vive em</span><span id="u4452-2"> Seu Distrito Oficial</span></p>
        <p id="u4452-7"><span id="u4452-4">De</span><span id="u4452-5"> </span><span id="u4452-6">Seu país de Origem</span></p>
       </div>
       <div class="clearfix grpelem" id="u4455-5"><!-- content -->
        <p id="u4455-3"><span id="u4455">Seguido por </span><span id="u4455-2">'N' Pessoas</span></p>
       </div>
       <div class="clearfix grpelem" id="u4458-4"><!-- content -->
        <p id="u4458-2">Detalhes</p>
       </div>
       <div class="clearfix grpelem" id="u4461-5"><!-- content -->
        <p id="u4461-3"><span id="u4461">Ver mais </span><span id="u4461-2">aqui</span></p>
       </div>
       <div class="museBGSize grpelem" id="u4920"><!-- simple frame --></div>
      </div>
      <div class="clearfix colelem" id="pu4937"><!-- group -->
       <div class="grpelem" id="u4937"><!-- simple frame --></div>
       <div class="clearfix grpelem" id="u4940-4"><!-- content -->
        <p id="u4940-2">Publicações</p>
       </div>
       <div class="clearfix grpelem" id="u4946-5"><!-- content -->
        <p id="u4946-3"><span id="u4946">Total de atividades </span><span id="u4946-2">50 M</span></p>
       </div>
       <div class="clearfix grpelem" id="u4949-5"><!-- content -->
        <p id="u4949-3"><span id="u4949">Gostos </span><span id="u4949-2">60 M</span></p>
       </div>
       <div class="clearfix grpelem" id="u4952-5"><!-- content -->
        <p id="u4952-3"><span id="u4952">Partilhas </span><span id="u4952-2">120 M</span></p>
       </div>
       <div class="clearfix grpelem" id="u4955-5"><!-- content -->
        <p id="u4955-3"><span id="u4955">Visualizações </span><span id="u4955-2">330 M</span></p>
       </div>
      </div>
     </div>
     <div class="clearfix grpelem" id="pu4963"><!-- column -->
      <div class="colelem" id="u4963"><!-- simple frame --></div>
      <div class="colelem" id="u4966"><!-- simple frame --></div>
     </div>
    </div>
    <div class="colelem" id="u4969"><!-- simple frame --></div>
    <div class="colelem" id="u4987"><!-- simple frame --></div>
   </div>
   <div class="verticalspacer" data-offset-top="2093" data-content-above-spacer="2093" data-content-below-spacer="32"></div>
  </div>
  <div class="preload_images">
   <img class="preload" src="images/icons8-user-filled-50%20(1)-u6448-r-fr.png?crc=114902342" alt=""/>
   <img class="preload" src="images/icons8-user-filled-50-u6448-fr.png?crc=4216544584" alt=""/>
   <img class="preload" src="images/icons8-bulleted-list-filled-50%20(1)-u6588-r-fr.png?crc=4095551244" alt=""/>
   <img class="preload" src="images/icons8-bulleted-list-filled-50-u6588-fr.png?crc=385998477" alt=""/>
   <img class="preload" src="images/icons8-price-tag-filled-50%20(1)-u6610-r-fr.png?crc=349681327" alt=""/>
   <img class="preload" src="images/icons8-price-tag-filled-50-u6610-fr.png?crc=3761798394" alt=""/>
   <img class="preload" src="images/icons8-user-groups-filled-50%20(1).png?crc=387000346" alt=""/>
   <img class="preload" src="images/icons8-user-groups-filled-50.png?crc=448874755" alt=""/>
   <img class="preload" src="images/icons8-help-50%20(1).png?crc=320904700" alt=""/>
   <img class="preload" src="images/icons8-help-50.png?crc=3787903515" alt=""/>
   <img class="preload" src="images/icons8-settings-filled-50%20(1).png?crc=347087800" alt=""/>
   <img class="preload" src="images/icons8-settings-filled-50.png?crc=4116914146" alt=""/>
   <img class="preload" src="images/icons8-exit-filled-50%20(1).png?crc=269451593" alt=""/>
   <img class="preload" src="images/icons8-exit-filled-50.png?crc=523631758" alt=""/>
   <img class="preload" src="images/icons8-technical-support-24-u6882-r-fr.png?crc=274936526" alt=""/>
   <img class="preload" src="images/icons8-technical-support-24%20(1).png?crc=507442715" alt=""/>
  </div>
  <!-- Other scripts -->
  <script type="text/javascript">
   // Decide whether to suppress missing file error or not based on preference setting
var suppressMissingFileError = false
</script>
  <script type="text/javascript">
   window.Muse.assets.check=function(c){if(!window.Muse.assets.checked){window.Muse.assets.checked=!0;var b={},d=function(a,b){if(window.getComputedStyle){var c=window.getComputedStyle(a,null);return c&&c.getPropertyValue(b)||c&&c[b]||""}if(document.documentElement.currentStyle)return(c=a.currentStyle)&&c[b]||a.style&&a.style[b]||"";return""},a=function(a){if(a.match(/^rgb/))return a=a.replace(/\s+/g,"").match(/([\d\,]+)/gi)[0].split(","),(parseInt(a[0])<<16)+(parseInt(a[1])<<8)+parseInt(a[2]);if(a.match(/^\#/))return parseInt(a.substr(1),
16);return 0},f=function(f){for(var g=document.getElementsByTagName("link"),j=0;j<g.length;j++)if("text/css"==g[j].type){var l=(g[j].href||"").match(/\/?css\/([\w\-]+\.css)\?crc=(\d+)/);if(!l||!l[1]||!l[2])break;b[l[1]]=l[2]}g=document.createElement("div");g.className="version";g.style.cssText="display:none; width:1px; height:1px;";document.getElementsByTagName("body")[0].appendChild(g);for(j=0;j<Muse.assets.required.length;){var l=Muse.assets.required[j],k=l.match(/([\w\-\.]+)\.(\w+)$/),i=k&&k[1]?
k[1]:null,k=k&&k[2]?k[2]:null;switch(k.toLowerCase()){case "css":i=i.replace(/\W/gi,"_").replace(/^([^a-z])/gi,"_$1");g.className+=" "+i;i=a(d(g,"color"));k=a(d(g,"backgroundColor"));i!=0||k!=0?(Muse.assets.required.splice(j,1),"undefined"!=typeof b[l]&&(i!=b[l]>>>24||k!=(b[l]&16777215))&&Muse.assets.outOfDate.push(l)):j++;g.className="version";break;case "js":j++;break;default:throw Error("Unsupported file type: "+k);}}c?c().jquery!="1.8.3"&&Muse.assets.outOfDate.push("jquery-1.8.3.min.js"):Muse.assets.required.push("jquery-1.8.3.min.js");
g.parentNode.removeChild(g);if(Muse.assets.outOfDate.length||Muse.assets.required.length)g="Alguns arquivos no servidor podem estar ausentes ou incorretos. Limpe o cache do navegador e tente novamente. Se o problema persistir, entre em contato com o autor do site.",f&&Muse.assets.outOfDate.length&&(g+="\nOut of date: "+Muse.assets.outOfDate.join(",")),f&&Muse.assets.required.length&&(g+="\nMissing: "+Muse.assets.required.join(",")),suppressMissingFileError?(g+="\nUse SuppressMissingFileError key in AppPrefs.xml to show missing file error pop up.",console.log(g)):g};location&&location.search&&location.search.match&&location.search.match(/muse_debug/gi)?
setTimeout(function(){f(!0)},5E3):f()}};
var muse_init=function(){require.config({baseUrl:"https://portalget.com/src/"});require(["jquery","museutils","whatinput","jquery.watch","jquery.musepolyfill.bgsize","jquery.musemenu","webpro","musewpslideshow","jquery.museoverlay","touchswipe","jquery.scrolleffects"],function(c){var $ = c;$(document).ready(function(){try{
window.Muse.assets.check($);/* body */
Muse.Utils.transformMarkupToFixBrowserProblemsPreInit();/* body */
Muse.Utils.prepHyperlinks(true);/* body */
Muse.Utils.resizeHeight('.browser_width');/* resize height */
Muse.Utils.requestAnimationFrame(function() { $('body').addClass('initialized'); });/* mark body as initialized */
Muse.Utils.makeButtonsVisibleAfterSettingMinWidth();/* body */
Muse.Utils.initWidget('.MenuBar', ['#bp_infinity'], function(elem) { return $(elem).museMenu(); });/* unifiedNavBar */
Muse.Utils.initWidget('#pamphletu25510', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_both',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:0,hideAllContentsFirst:true,triggersOnTop:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu25510 */
Muse.Utils.initWidget('#pamphletu25666', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_click',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:0,hideAllContentsFirst:true,triggersOnTop:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu25666 */
Muse.Utils.initWidget('#pamphletu25642', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_both',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:0,hideAllContentsFirst:true,triggersOnTop:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu25642 */
Muse.Utils.initWidget('#pamphletu10618', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_both',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:0,hideAllContentsFirst:true,triggersOnTop:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu10618 */
Muse.Utils.fullPage('#page');/* 100% height page */
$('#u2856-bw').registerPositionScrollEffect([{"in":[-Infinity,0],"speed":[null,1]},{"in":[0,Infinity],"speed":[null,0]}]);/* scroll effect */
$('#u2865').registerPositionScrollEffect([{"in":[-Infinity,0],"speed":[1,1]},{"in":[0,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u4977').registerPositionScrollEffect([{"in":[-Infinity,743.8],"speed":[0,1]},{"in":[743.8,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u7973').registerPositionScrollEffect([{"in":[-Infinity,-0.03],"speed":[1,1]},{"in":[-0.03,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u7974').registerPositionScrollEffect([{"in":[-Infinity,-0.03],"speed":[0,1]},{"in":[-0.03,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u7975').registerPositionScrollEffect([{"in":[-Infinity,-0.1],"speed":[1,1]},{"in":[-0.1,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u7976-4').registerPositionScrollEffect([{"in":[-Infinity,-0.05],"speed":[0,1]},{"in":[-0.05,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u8595').registerPositionScrollEffect([{"in":[-Infinity,-0.68],"speed":[1,1]},{"in":[-0.68,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#pamphletu25510').registerPositionScrollEffect([{"in":[-Infinity,-0.42],"speed":[0,1]},{"in":[-0.42,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#pamphletu25642').registerPositionScrollEffect([{"in":[-Infinity,-1.55],"speed":[0,1]},{"in":[-1.55,Infinity],"speed":[0,0]}]);/* scroll effect */
Muse.Utils.showWidgetsWhenReady();/* body */
Muse.Utils.transformMarkupToFixBrowserProblems();/* body */
}catch(b){if(b&&"function"==typeof b.notify?b.notify():Muse.Assert.fail("Error calling selector function: "+b),false)throw b;}})})};

</script>
  <!-- RequireJS script -->
  <script src="https://portalget.com/src/scripts/require.js?crc=7928878" type="text/javascript" async data-main="https://portalget.com/src/scripts/museconfig.js?crc=310584261" onload="if (requirejs) requirejs.onError = function(requireType, requireModule) { if (requireType && requireType.toString && requireType.toString().indexOf && 0 <= requireType.toString().indexOf('#scripterror')) window.Muse.assets.check(); }" onerror="window.Muse.assets.check();"></script>
   </body>
</html>
