<!DOCTYPE html>
<html class="nojs html css_verticalspacer" lang="pt-BR">
 <head>

  <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>
  <meta name="generator" content="2018.1.0.386"/>
  
  <script type="text/javascript">
   // Update the 'nojs'/'js' class on the html node
document.documentElement.className = document.documentElement.className.replace(/\bnojs\b/g, 'js');

// Check that all required assets are uploaded and up-to-date
if(typeof Muse == "undefined") window.Muse = {}; window.Muse.assets = {"required":["museutils.js", "museconfig.js", "jquery.watch.js", "require.js", "jquery.musepolyfill.bgsize.js", "webpro.js", "musewpslideshow.js", "jquery.museoverlay.js", "touchswipe.js", "jquery.musemenu.js", "jquery.scrolleffects.js", "create.css"], "outOfDate":[]};
</script>
  
  <title>create</title>
  <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/site_global.css?crc=444006867"/>
  <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/create.css?crc=3814697141" id="pagesheet"/>
  <!-- JS includes -->
  <!--[if lt IE 9]>
  <script src="scripts/html5shiv.js?crc=4241844378" type="text/javascript"></script>
  <![endif]-->
   </head>
 <body>

  <div class="clearfix" id="page"><!-- group -->
   <div class="clearfix grpelem" id="pu22007"><!-- group -->
    <div class="browser_width mse_pre_init" id="u22007-bw">
     <div class="transition shadow" id="u22007"><!-- simple frame --></div>
    </div>
    <div class="museBGSize mse_pre_init" id="u22011"><!-- simple frame --></div>
    <div class="PamphletWidget clearfix mse_pre_init" id="pamphletu25015"><!-- none box -->
     <div class="popup_anchor" id="u25024popup">
      <div class="ContainerGroup clearfix" id="u25024"><!-- stack box -->
       <div class="Container invi rounded-corners clearfix grpelem" id="u25025"><!-- column -->
        <div class="clearfix colelem" id="pu25033"><!-- group -->
         <div class="rounded-corners clearfix grpelem" id="u25033"><!-- group -->
          <div class="museBGSize grpelem" id="u25045"><!-- simple frame --></div>
          <div class="clearfix grpelem" id="u25027-4"><!-- content -->
           <p>Caixa de entrada ( 0 )</p>
          </div>
          <div class="museBGSize grpelem" id="u25032"><!-- simple frame --></div>
          <div class="museBGSize grpelem" id="u25038"><!-- simple frame --></div>
         </div>
         <div class="grpelem" id="u25051"><!-- custom html -->
          <input type="text" style="width:655px; 
height:25px; box-shadow: 0 0 3px #508ab2;
 margin:1px; font-size:14px; padding:0px 15px 0px 15px;" placeholder="Procurar.." ></input>
         </div>
         <div class="grpelem" id="u25029"><!-- simple frame --></div>
         <div class="museBGSize grpelem" id="u25026"><!-- simple frame --></div>
         <div class="clearfix grpelem" id="u25046-4"><!-- content -->
          <p>Este é um exemplo de texto recebido de mensagem, Lorem isupum</p>
         </div>
         <div class="clearfix grpelem" id="u25048-4"><!-- content -->
          <p>Agostinho De Pina Ramos</p>
         </div>
         <div class="grpelem" id="u25030"><!-- simple frame --></div>
         <div class="grpelem" id="u25044"><!-- custom html -->
          <input type="checkbox" value="" >
         </div>
         <div class="grpelem" id="u25041"><!-- simple frame --></div>
         <div class="museBGSize grpelem" id="u25071"><!-- simple frame --></div>
         <div class="clearfix grpelem" id="u25039-4"><!-- content -->
          <p>Este é um exemplo de texto recebido de mensagem, Lorem isupum</p>
         </div>
         <div class="clearfix grpelem" id="u25028-4"><!-- content -->
          <p>Agostinho De Pina Ramos</p>
         </div>
         <div class="grpelem" id="u25042"><!-- simple frame --></div>
         <div class="grpelem" id="u25037"><!-- custom html -->
          <input type="checkbox" value="" >
         </div>
         <div class="museBGSize grpelem" id="u25049"><!-- simple frame --></div>
         <div class="museBGSize grpelem" id="u25031"><!-- simple frame --></div>
         <div class="museBGSize grpelem" id="u25050"><!-- simple frame --></div>
         <div class="PamphletWidget clearfix grpelem" id="pamphletu25052"><!-- none box -->
          <div class="popup_anchor" id="u25059popup">
           <div class="ContainerGroup clearfix" id="u25059"><!-- stack box -->
            <div class="Container invi clearfix grpelem" id="u25060"><!-- group -->
             <div class="clearfix grpelem" id="pu25062"><!-- column -->
              <div class="colelem" id="u25062"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
              <div class="colelem" id="u25065"><!-- custom html -->
               <input type="checkbox" value="">
              </div>
              <div class="colelem" id="u25061"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
              <div class="colelem" id="u25067"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
             </div>
             <div class="clearfix grpelem" id="pu25064-4"><!-- column -->
              <div class="clearfix colelem" id="u25064-4"><!-- content -->
               <p>Alert icon</p>
              </div>
              <div class="clearfix colelem" id="u25066-4"><!-- content -->
               <p>Alert song</p>
              </div>
              <div class="clearfix colelem" id="u25063-4"><!-- content -->
               <p>Auto refresh</p>
              </div>
              <div class="clearfix colelem" id="u25068-4"><!-- content -->
               <p>Desativar</p>
              </div>
             </div>
            </div>
           </div>
          </div>
          <div class="ThumbGroup clearfix grpelem" id="u25057"><!-- none box -->
           <div class="popup_anchor" id="u25058popup">
            <div class="Thumb popup_element museBGSize" id="u25058"><!-- simple frame --></div>
           </div>
          </div>
         </div>
        </div>
        <div class="clearfix colelem" id="pu25040"><!-- group -->
         <div class="grpelem" id="u25040"><!-- simple frame --></div>
         <div class="museBGSize grpelem" id="u25043"><!-- simple frame --></div>
         <div class="clearfix grpelem" id="u25047-4"><!-- content -->
          <p>Este é um exemplo de texto recebido de mensagem, Lorem isupum</p>
         </div>
         <div class="clearfix grpelem" id="u25035-4"><!-- content -->
          <p>Agostinho De Pina Ramos</p>
         </div>
         <div class="grpelem" id="u25036"><!-- simple frame --></div>
         <div class="grpelem" id="u25034"><!-- custom html -->
          <input type="checkbox" value="" >
         </div>
        </div>
       </div>
      </div>
     </div>
     <div class="ThumbGroup clearfix grpelem" id="u25016"><!-- none box -->
      <div class="popup_anchor" id="u25017popup">
       <div class="Thumb popup_element" id="u25017"><!-- simple frame --></div>
      </div>
     </div>
    </div>
   </div>
   <div class="clearfix grpelem" id="pu22245"><!-- column -->
    <div class="colelem" id="u22245"><!-- custom html -->
     <input type="text" style="width:186px; 
height:23px; box-shadow: 0 0 3px #508ab2;
 margin:1px; font-size:12px; padding:0px 2px 0px 3px;" placeholder="Pesquisar etiquetas" ></input>
    </div>
    <div class="clearfix colelem" id="u22046"><!-- group -->
     <div class="clearfix grpelem" id="u23305"><!-- group -->
      <div class="clearfix grpelem" id="u23307-4"><!-- content -->
       <p><span id="u23307">Javascript</span></p>
      </div>
      <div class="grpelem" id="u23314"><!-- custom html -->
       <input class="wrapped-input" type="checkbox" value="1" id="widgetu22329_input" name="custom_U22329" tabindex="4">

<style>
#widgetu22329_input {
    position: absolute;
    width: 16px;
    height: 16px;
    min-height: 0px;
}
</style>

      </div>
     </div>
    </div>
   </div>
   <div class="clearfix grpelem" id="pu22253"><!-- column -->
    <div class="colelem" id="u22253"><!-- custom html -->
     <input type="text" style="width:565px; 
height:23px; box-shadow: 0 0 3px #508ab2;
 margin:1px; font-size:12px; padding:0px 2px 0px 3px;" placeholder="Escolher título" ></input>
    </div>
    <div class="colelem" id="u22258"><!-- custom html -->
     <input type="text" style="width:565px; 
height:23px; box-shadow: 0 0 3px #508ab2;
 margin:1px; font-size:12px; padding:0px 2px 0px 3px;" placeholder="URL link (*opcional)" ></input>
    </div>
    <div class="colelem" id="u22241"><!-- custom html -->
     <textarea class="wrapped-input" style="width:570px; height:285px; background-color:#fff;"
id="widgetu22142_input" name="custom_U22142" tabindex="1"></textarea>

<style>
#widgetu22142_input {
    border-style: inset;
    border-width: 1px;
    border-color:#508AB2;
}

#widgetu22142_input::-webkit-scrollbar {
    width: 10px;
}

#widgetu22142_input::-webkit-scrollbar-track {
    background: #f1f1f1; 
}

#widgetu22142_input::-webkit-scrollbar-thumb {
    background: #888; 
}

#widgetu22142_input::-webkit-scrollbar-thumb:hover {
    background: #555; 
}

</style>
    </div>
    <div class="clearfix colelem" id="u22043"><!-- column -->
     <div class="museBGSize colelem" id="u22263"><!-- simple frame --></div>
     <div class="clearfix colelem" id="u22274-4"><!-- content -->
      <p>Carregar um ficheiros aqui</p>
     </div>
    </div>
   </div>
   <div class="clearfix grpelem" id="pu22014"><!-- group -->
    <div class="mse_pre_init" id="u22014"><!-- simple frame --></div>
    <div class="museBGSize mse_pre_init" id="u22008"><!-- simple frame --></div>
    <div class="PamphletWidget clearfix mse_pre_init" id="pamphletu24940"><!-- none box -->
     <div class="popup_anchor" id="u24943popup">
      <div class="ContainerGroup clearfix" id="u24943"><!-- stack box -->
       <div class="Container invi rounded-corners clearfix grpelem" id="u24944"><!-- column -->
        <div class="clearfix colelem" id="pu25007"><!-- group -->
         <div class="grpelem" id="u25007"><!-- simple frame --></div>
         <div class="museBGSize rounded-corners grpelem" id="u25006"><!-- simple frame --></div>
         <div class="clearfix grpelem" id="u24945-4"><!-- content -->
          <p>agostinhopina95@gmail.com</p>
         </div>
         <div class="clearfix grpelem" id="u25004-4"><!-- content -->
          <p>Agostinho De Pina Ramos</p>
         </div>
        </div>
        <div class="clearfix colelem" id="u25008"><!-- column -->
         <nav class="MenuBar clearfix colelem" id="menuu24946"><!-- vertical box -->
          <div class="MenuItemContainer clearfix colelem" id="u24954"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24957"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u24960"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24959-4"><!-- content -->
             <p>Ver o meu perfil</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24975"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24976"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u24978"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24979-4"><!-- content -->
             <p>Editor Online</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24947"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24950"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u24953"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24952-4"><!-- content -->
             <p>Criar uma etiqueta</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24968"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24969"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u24971"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24970-4"><!-- content -->
             <p>Criar um grupo</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24961"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24962"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u24964"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24965-4"><!-- content -->
             <p>Ver questões</p>
            </div>
           </div>
          </div>
         </nav>
         <div class="colelem" id="u25005"><!-- simple frame --></div>
         <nav class="MenuBar clearfix colelem" id="menuu24982"><!-- vertical box -->
          <div class="MenuItemContainer clearfix colelem" id="u24990"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24993"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u24995"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24994-4"><!-- content -->
             <p>Definições</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24983"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24986"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u24987"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24989-4"><!-- content -->
             <p>Terminar sessão</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24997"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24998"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u25000"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u25001-4"><!-- content -->
             <p>Ajuda</p>
            </div>
           </div>
          </div>
         </nav>
        </div>
       </div>
      </div>
     </div>
     <div class="ThumbGroup clearfix grpelem" id="u25009"><!-- none box -->
      <div class="popup_anchor" id="u25010popup">
       <div class="Thumb popup_element" id="u25010"><!-- simple frame --></div>
      </div>
     </div>
    </div>
    <div class="PamphletWidget clearfix mse_pre_init" id="pamphletu25072"><!-- none box -->
     <div class="popup_anchor" id="u25079popup">
      <div class="ContainerGroup clearfix" id="u25079"><!-- stack box -->
       <div class="Container invi rounded-corners clearfix grpelem" id="u25080"><!-- column -->
        <div class="clearfix colelem" id="pu25109"><!-- group -->
         <div class="rounded-corners grpelem" id="u25109"><!-- simple frame --></div>
         <div class="grpelem" id="u25082"><!-- simple frame --></div>
         <div class="museBGSize rounded-corners grpelem" id="u25117"><!-- content --></div>
         <div class="clearfix grpelem" id="u25119-6"><!-- content -->
          <p><span id="u25119">Agostinho de Pina Ramos</span> publicou em etiqueta <span id="u25119-3">Java.</span></p>
         </div>
         <div class="clearfix grpelem" id="u25108-4"><!-- content -->
          <p>Ontem ás 16h00</p>
         </div>
         <div class="museBGSize grpelem" id="u25115"><!-- simple frame --></div>
         <div class="grpelem" id="u25110"><!-- simple frame --></div>
         <div class="grpelem" id="u25084"><!-- simple frame --></div>
         <div class="museBGSize rounded-corners grpelem" id="u25107"><!-- content --></div>
         <div class="clearfix grpelem" id="u25106-6"><!-- content -->
          <p><span id="u25106">Agostinho de Pina Ramos</span> publicou em etiqueta <span id="u25106-3">Java.</span></p>
         </div>
         <div class="clearfix grpelem" id="u25111-4"><!-- content -->
          <p>Ontem ás 16h00</p>
         </div>
         <div class="museBGSize grpelem" id="u25105"><!-- simple frame --></div>
         <div class="grpelem" id="u25085"><!-- simple frame --></div>
         <div class="PamphletWidget clearfix grpelem" id="pamphletu25086"><!-- none box -->
          <div class="popup_anchor" id="u25093popup">
           <div class="ContainerGroup clearfix" id="u25093"><!-- stack box -->
            <div class="Container invi clearfix grpelem" id="u25094"><!-- group -->
             <div class="clearfix grpelem" id="pu25095"><!-- column -->
              <div class="colelem" id="u25095"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
              <div class="colelem" id="u25097"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
              <div class="colelem" id="u25098"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
              <div class="colelem" id="u25101"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
             </div>
             <div class="clearfix grpelem" id="pu25099-4"><!-- column -->
              <div class="clearfix colelem" id="u25099-4"><!-- content -->
               <p>Alert icon</p>
              </div>
              <div class="clearfix colelem" id="u25102-4"><!-- content -->
               <p>Alert song</p>
              </div>
              <div class="clearfix colelem" id="u25100-4"><!-- content -->
               <p>Auto refresh</p>
              </div>
              <div class="clearfix colelem" id="u25096-4"><!-- content -->
               <p>Desativar</p>
              </div>
             </div>
            </div>
           </div>
          </div>
          <div class="ThumbGroup clearfix grpelem" id="u25089"><!-- none box -->
           <div class="popup_anchor" id="u25090popup">
            <div class="Thumb popup_element museBGSize" id="u25090"><!-- simple frame --></div>
           </div>
          </div>
         </div>
         <div class="clearfix grpelem" id="u25114-4"><!-- content -->
          <p>Notificações</p>
         </div>
        </div>
        <div class="clearfix colelem" id="pu25116"><!-- group -->
         <div class="grpelem" id="u25116"><!-- simple frame --></div>
         <div class="museBGSize rounded-corners grpelem" id="u25113"><!-- content --></div>
         <div class="clearfix grpelem" id="u25081-6"><!-- content -->
          <p><span id="u25081">Agostinho de Pina Ramos</span> publicou em etiqueta <span id="u25081-3">Java.</span></p>
         </div>
         <div class="clearfix grpelem" id="u25112-4"><!-- content -->
          <p>Ontem ás 16h00</p>
         </div>
         <div class="museBGSize grpelem" id="u25118"><!-- simple frame --></div>
         <div class="grpelem" id="u25083"><!-- simple frame --></div>
        </div>
       </div>
      </div>
     </div>
     <div class="ThumbGroup clearfix grpelem" id="u25073"><!-- none box -->
      <div class="popup_anchor" id="u25074popup">
       <div class="Thumb popup_element" id="u25074"><!-- simple frame --></div>
      </div>
     </div>
    </div>
   </div>
   <div class="clearfix grpelem" id="pu22049"><!-- column -->
    <div class="colelem" id="u22049"><!-- custom html -->
     <button type="button" style="
 background: #508ab2;
  background-image: -webkit-linear-gradient(top, #508ab2, #2980b9);
  background-image: -moz-linear-gradient(top, #508ab2, #2980b9);
  background-image: -ms-linear-gradient(top, #508ab2, #2980b9);
  background-image: -o-linear-gradient(top, #508ab2, #2980b9);
  background-image: linear-gradient(to bottom, #508ab2, #2980b9);
  text-shadow: 1px 1px 3px #666666;
  -webkit-box-shadow: 0px 1px 3px #666666;
  -moz-box-shadow: 0px 1px 3px #666666;
  box-shadow: 0px 1px 3px #666666;
  font-family: Arial;
  color: #ffffff;
  font-size: 14px;
  padding: 5px 10px;
  background: #508ab2;
  text-decoration: none;
" >Carregar</button>

    </div>
    <div class="clearfix colelem" id="u22250"><!-- group -->
     <div class="clearfix grpelem" id="pu22386"><!-- column -->
      <div class="colelem" id="u22386"><!-- custom html -->
       <input class="wrapped-input" type="checkbox" value="1" id="widgetu22329_input" name="custom_U22329" tabindex="4">

<style>
#widgetu22329_input {
    position: absolute;
    width: 16px;
    height: 16px;
    min-height: 0px;
}
</style>

      </div>
      <div class="colelem" id="u22393"><!-- custom html -->
       <input class="wrapped-input" type="checkbox" value="1" id="widgetu22329_input" name="custom_U22329" tabindex="4">

<style>
#widgetu22329_input {
    position: absolute;
    width: 16px;
    height: 16px;
    min-height: 0px;
}
</style>

      </div>
      <div class="colelem" id="u22401"><!-- custom html -->
       <input class="wrapped-input" type="checkbox" value="1" id="widgetu22329_input" name="custom_U22329" tabindex="4">

<style>
#widgetu22329_input {
    position: absolute;
    width: 16px;
    height: 16px;
    min-height: 0px;
}
</style>

      </div>
      <div class="colelem" id="u22409"><!-- custom html -->
       <input class="wrapped-input" type="checkbox" value="1" id="widgetu22329_input" name="custom_U22329" tabindex="4">

<style>
#widgetu22329_input {
    position: absolute;
    width: 16px;
    height: 16px;
    min-height: 0px;
}
</style>

      </div>
      <div class="colelem" id="u22417"><!-- custom html -->
       <input class="wrapped-input" type="checkbox" value="1" id="widgetu22329_input" name="custom_U22329" tabindex="4">

<style>
#widgetu22329_input {
    position: absolute;
    width: 16px;
    height: 16px;
    min-height: 0px;
}
</style>

      </div>
      <div class="colelem" id="u22425"><!-- custom html -->
       <input class="wrapped-input" type="checkbox" value="1" id="widgetu22329_input" name="custom_U22329" tabindex="4">

<style>
#widgetu22329_input {
    position: absolute;
    width: 16px;
    height: 16px;
    min-height: 0px;
}
</style>

      </div>
     </div>
     <div class="clearfix grpelem" id="pu22390-4"><!-- column -->
      <div class="clearfix colelem" id="u22390-4"><!-- content -->
       <p>Título</p>
      </div>
      <div class="clearfix colelem" id="u22394-4"><!-- content -->
       <p>Subtítulo</p>
      </div>
      <div class="clearfix colelem" id="u22402-4"><!-- content -->
       <p>Upload</p>
      </div>
      <div class="clearfix colelem" id="u22410-4"><!-- content -->
       <p>Caixa de texto</p>
      </div>
      <div class="clearfix colelem" id="u22418-4"><!-- content -->
       <p>URL link</p>
      </div>
      <div class="clearfix colelem" id="u22426-4"><!-- content -->
       <p>Video (Youtube)</p>
      </div>
     </div>
    </div>
   </div>
   <div class="clearfix grpelem" id="pu22009"><!-- group -->
    <div class="museBGSize rounded-corners mse_pre_init" id="u22009"><!-- simple frame --></div>
    <div class="museBGSize mse_pre_init" id="u22010"><!-- simple frame --></div>
    <div class="shadow rounded-corners mse_pre_init" id="u22012"><!-- simple frame --></div>
    <div class="clearfix mse_pre_init" id="u22013-4"><!-- content -->
     <p id="u22013-2">3</p>
    </div>
    <div class="museBGSize mse_pre_init" id="u22015"><!-- simple frame --></div>
    <div class="museBGSize mse_pre_init" id="u22016"><!-- simple frame --></div>
    <div class="shadow rounded-corners mse_pre_init" id="u22017"><!-- simple frame --></div>
    <div class="clearfix mse_pre_init" id="u22018-4"><!-- content -->
     <p id="u22018-2">5</p>
    </div>
   </div>
   <div class="verticalspacer" data-offset-top="573" data-content-above-spacer="573" data-content-below-spacer="22"></div>
  </div>
  <div class="preload_images">
   <img class="preload" src="images/icons8-user-filled-50%20(1)-u6448-r-fr.png?crc=114902342" alt=""/>
   <img class="preload" src="images/icons8-user-filled-50-u6448-fr.png?crc=4216544584" alt=""/>
   <img class="preload" src="images/icons8-bulleted-list-filled-50%20(1)-u6588-r-fr.png?crc=4095551244" alt=""/>
   <img class="preload" src="images/icons8-bulleted-list-filled-50-u6588-fr.png?crc=385998477" alt=""/>
   <img class="preload" src="images/icons8-price-tag-filled-50%20(1)-u6610-r-fr.png?crc=349681327" alt=""/>
   <img class="preload" src="images/icons8-price-tag-filled-50-u6610-fr.png?crc=3761798394" alt=""/>
   <img class="preload" src="images/icons8-user-groups-filled-50%20(1).png?crc=387000346" alt=""/>
   <img class="preload" src="images/icons8-user-groups-filled-50.png?crc=448874755" alt=""/>
   <img class="preload" src="images/icons8-help-50%20(1).png?crc=320904700" alt=""/>
   <img class="preload" src="images/icons8-help-50.png?crc=3787903515" alt=""/>
   <img class="preload" src="images/icons8-settings-filled-50%20(1).png?crc=347087800" alt=""/>
   <img class="preload" src="images/icons8-settings-filled-50.png?crc=4116914146" alt=""/>
   <img class="preload" src="images/icons8-exit-filled-50%20(1).png?crc=269451593" alt=""/>
   <img class="preload" src="images/icons8-exit-filled-50.png?crc=523631758" alt=""/>
   <img class="preload" src="images/icons8-technical-support-24-u6882-r-fr.png?crc=274936526" alt=""/>
   <img class="preload" src="images/icons8-technical-support-24%20(1).png?crc=507442715" alt=""/>
  </div>
  <!-- Other scripts -->
  <script type="text/javascript">
   // Decide whether to suppress missing file error or not based on preference setting
var suppressMissingFileError = false
</script>
  <script type="text/javascript">
   window.Muse.assets.check=function(c){if(!window.Muse.assets.checked){window.Muse.assets.checked=!0;var b={},d=function(a,b){if(window.getComputedStyle){var c=window.getComputedStyle(a,null);return c&&c.getPropertyValue(b)||c&&c[b]||""}if(document.documentElement.currentStyle)return(c=a.currentStyle)&&c[b]||a.style&&a.style[b]||"";return""},a=function(a){if(a.match(/^rgb/))return a=a.replace(/\s+/g,"").match(/([\d\,]+)/gi)[0].split(","),(parseInt(a[0])<<16)+(parseInt(a[1])<<8)+parseInt(a[2]);if(a.match(/^\#/))return parseInt(a.substr(1),
16);return 0},f=function(f){for(var g=document.getElementsByTagName("link"),j=0;j<g.length;j++)if("text/css"==g[j].type){var l=(g[j].href||"").match(/\/?css\/([\w\-]+\.css)\?crc=(\d+)/);if(!l||!l[1]||!l[2])break;b[l[1]]=l[2]}g=document.createElement("div");g.className="version";g.style.cssText="display:none; width:1px; height:1px;";document.getElementsByTagName("body")[0].appendChild(g);for(j=0;j<Muse.assets.required.length;){var l=Muse.assets.required[j],k=l.match(/([\w\-\.]+)\.(\w+)$/),i=k&&k[1]?
k[1]:null,k=k&&k[2]?k[2]:null;switch(k.toLowerCase()){case "css":i=i.replace(/\W/gi,"_").replace(/^([^a-z])/gi,"_$1");g.className+=" "+i;i=a(d(g,"color"));k=a(d(g,"backgroundColor"));i!=0||k!=0?(Muse.assets.required.splice(j,1),"undefined"!=typeof b[l]&&(i!=b[l]>>>24||k!=(b[l]&16777215))&&Muse.assets.outOfDate.push(l)):j++;g.className="version";break;case "js":j++;break;default:throw Error("Unsupported file type: "+k);}}c?c().jquery!="1.8.3"&&Muse.assets.outOfDate.push("jquery-1.8.3.min.js"):Muse.assets.required.push("jquery-1.8.3.min.js");
g.parentNode.removeChild(g);if(Muse.assets.outOfDate.length||Muse.assets.required.length)g="Alguns arquivos no servidor podem estar ausentes ou incorretos. Limpe o cache do navegador e tente novamente. Se o problema persistir, entre em contato com o autor do site.",f&&Muse.assets.outOfDate.length&&(g+="\nOut of date: "+Muse.assets.outOfDate.join(",")),f&&Muse.assets.required.length&&(g+="\nMissing: "+Muse.assets.required.join(",")),suppressMissingFileError?(g+="\nUse SuppressMissingFileError key in AppPrefs.xml to show missing file error pop up.",console.log(g)):g};location&&location.search&&location.search.match&&location.search.match(/muse_debug/gi)?
setTimeout(function(){f(!0)},5E3):f()}};
var muse_init=function(){require.config({baseUrl:"https://portalget.com/src/"});require(["jquery","museutils","whatinput","jquery.watch","jquery.musepolyfill.bgsize","webpro","musewpslideshow","jquery.museoverlay","touchswipe","jquery.musemenu","jquery.scrolleffects"],function(c){var $ = c;$(document).ready(function(){try{
window.Muse.assets.check($);/* body */
Muse.Utils.transformMarkupToFixBrowserProblemsPreInit();/* body */
Muse.Utils.prepHyperlinks(true);/* body */
Muse.Utils.resizeHeight('.browser_width');/* resize height */
Muse.Utils.requestAnimationFrame(function() { $('body').addClass('initialized'); });/* mark body as initialized */
Muse.Utils.makeButtonsVisibleAfterSettingMinWidth();/* body */
Muse.Utils.initWidget('#pamphletu25052', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_click',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:0,hideAllContentsFirst:true,triggersOnTop:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu25052 */
Muse.Utils.initWidget('#pamphletu25015', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_click',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:0,hideAllContentsFirst:true,triggersOnTop:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu25015 */
Muse.Utils.initWidget('.MenuBar', ['#bp_infinity'], function(elem) { return $(elem).museMenu(); });/* unifiedNavBar */
Muse.Utils.initWidget('#pamphletu24940', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_both',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:0,hideAllContentsFirst:true,triggersOnTop:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu24940 */
Muse.Utils.initWidget('#pamphletu25086', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_click',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:0,hideAllContentsFirst:true,triggersOnTop:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu25086 */
Muse.Utils.initWidget('#pamphletu25072', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_both',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:0,hideAllContentsFirst:true,triggersOnTop:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu25072 */
Muse.Utils.fullPage('#page');/* 100% height page */
$('#u22007-bw').registerPositionScrollEffect([{"in":[-Infinity,-0.05],"speed":[null,1]},{"in":[-0.05,Infinity],"speed":[null,0]}]);/* scroll effect */
$('#u22011').registerPositionScrollEffect([{"in":[-Infinity,-0.05],"speed":[1,1]},{"in":[-0.05,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#pamphletu25015').registerPositionScrollEffect([{"in":[-Infinity,0.43],"speed":[0,1]},{"in":[0.43,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u22014').registerPositionScrollEffect([{"in":[-Infinity,-0.55],"speed":[1,1]},{"in":[-0.55,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u22008').registerPositionScrollEffect([{"in":[-Infinity,-0.05],"speed":[1,1]},{"in":[-0.05,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#pamphletu24940').registerPositionScrollEffect([{"in":[-Infinity,0.43],"speed":[0,1]},{"in":[0.43,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#pamphletu25072').registerPositionScrollEffect([{"in":[-Infinity,-0.7],"speed":[0,1]},{"in":[-0.7,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u22009').registerPositionScrollEffect([{"in":[-Infinity,-0.05],"speed":[1,1]},{"in":[-0.05,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u22010').registerPositionScrollEffect([{"in":[-Infinity,-0.05],"speed":[1,1]},{"in":[-0.05,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u22012').registerPositionScrollEffect([{"in":[-Infinity,-0.05],"speed":[1,1]},{"in":[-0.05,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u22013-4').registerPositionScrollEffect([{"in":[-Infinity,-0.05],"speed":[0,1]},{"in":[-0.05,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u22015').registerPositionScrollEffect([{"in":[-Infinity,-0.05],"speed":[1,1]},{"in":[-0.05,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u22016').registerPositionScrollEffect([{"in":[-Infinity,-0.05],"speed":[0,1]},{"in":[-0.05,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u22017').registerPositionScrollEffect([{"in":[-Infinity,-0.13],"speed":[1,1]},{"in":[-0.13,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#u22018-4').registerPositionScrollEffect([{"in":[-Infinity,-0.08],"speed":[0,1]},{"in":[-0.08,Infinity],"speed":[0,0]}]);/* scroll effect */
Muse.Utils.showWidgetsWhenReady();/* body */
Muse.Utils.transformMarkupToFixBrowserProblems();/* body */
}catch(b){if(b&&"function"==typeof b.notify?b.notify():Muse.Assert.fail("Error calling selector function: "+b),false)throw b;}})})};

</script>
  <!-- RequireJS script -->
  <script src="https://portalget.com/src/scripts/require.js?crc=7928878" type="text/javascript" async data-main="https://portalget.com/src/scripts/museconfig.js?crc=310584261" onload="if (requirejs) requirejs.onError = function(requireType, requireModule) { if (requireType && requireType.toString && requireType.toString().indexOf && 0 <= requireType.toString().indexOf('#scripterror')) window.Muse.assets.check(); }" onerror="window.Muse.assets.check();"></script>
   </body>
</html>
