<!DOCTYPE html>
   <html class="nojs html css_verticalspacer" lang="<?php echo $mcs->st_lang; ?>" >
    <head>
    <meta name="generator" content="2018.1.0.386"/>
    <script type="text/javascript" >
    document.documentElement.className = document.documentElement.className.replace(/\bnojs\b/g, 'js');
    if(typeof Muse == "undefined") window.Muse = {}; window.Muse.assets = {"required":["museutils.js", "museconfig.js", "jquery.musepolyfill.bgsize.js", "jquery.watch.js", "webpro.js", "musewpslideshow.js", "jquery.museoverlay.js", "touchswipe.js", "require.js", "jquery.musemenu.js", "jquery.scrolleffects.js", "home.css"], "outOfDate":[]};
    </script>
  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" >
    <meta name="Description" content="<?php echo $mcs->st_title; ?>" />
    <meta name="<?php echo $mcs->st_autor; ?>" content="Portalget Inc">
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/site_global.css?crc=444006867"/>
    <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/homevisite.css?crc=3963466983" id="pagesheet"/>
    <link rel="shortcut icon" href="<?php echo $mcs->st_favicon; ?>" type="image/x-icon"/>
    <title><?php echo $mcs->st_title; ?></title>
   </head>
 <body>

  <div class="clearfix" id="page"><!-- group -->
   <div class="clearfix grpelem" id="pu2583"><!-- group -->
    <div class="mse_pre_init" id="u2583"><!-- simple frame --></div>
    <div class="mse_pre_init" id="u2584"><!-- simple frame --></div>
    <div class="mse_pre_init" id="u2585"><!-- simple frame --></div>
    <div class="mse_pre_init" id="u2595"><!-- simple frame --></div>
    <div class="clearfix mse_pre_init" id="u2597-7"><!-- content -->
     <p>Privacidade · Termos · Cookies · Português (Portugal) · mais</p>
     <p>&nbsp;</p>
     <p>Copyright 2017 © Portalget, Inc.echo</p>
    </div>
    <div class="mse_pre_init" id="u2598"><!-- simple frame --></div>
    <div class="browser_width mse_pre_init" id="u2602-bw">
     <div class="transition shadow" id="u2602"><!-- simple frame --></div>
    </div>
    <div class="mse_pre_init" id="u2605"><!-- simple frame --></div>
    <div class="museBGSize mse_pre_init" id="u2606"><!-- simple frame --></div>
    <div class="museBGSize mse_pre_init" id="u2611"><!-- simple frame --></div>
    <div class="mse_pre_init" id="u2586"><!-- simple frame --></div>
    <div class="museBGSize mse_pre_init" id="u2587"><!-- simple frame --></div>
    <div class="mse_pre_init" id="u2588"><!-- simple frame --></div>
    <div class="museBGSize mse_pre_init" id="u2589"><!-- simple frame --></div>
    <div class="mse_pre_init" id="u2590"><!-- simple frame --></div>
    <div class="museBGSize mse_pre_init" id="u2591"><!-- simple frame --></div>
    <div class="museBGSize mse_pre_init" id="u2689"><!-- content --></div>
    <div id="u6086"><!-- custom html -->
     <button type="button" style="
 background: #508ab2;
  background-image: -webkit-linear-gradient(top, #508ab2, #2980b9);
  background-image: -moz-linear-gradient(top, #508ab2, #2980b9);
  background-image: -ms-linear-gradient(top, #508ab2, #2980b9);
  background-image: -o-linear-gradient(top, #508ab2, #2980b9);
  background-image: linear-gradient(to bottom, #508ab2, #2980b9);
  text-shadow: 1px 1px 3px #666666;
  -webkit-box-shadow: 0px 1px 3px #666666;
  -moz-box-shadow: 0px 1px 3px #666666;
  box-shadow: 0px 1px 3px #666666;
  font-family: Arial;
  color: #ffffff;
  font-size: 14px;
  padding: 5px 10px;
  background: #508ab2;
  text-decoration: none;
" >Entrar</button>

    </div>
    <div id="u6091"><!-- custom html -->
     <input type="text" style="width:172px; 
height:25px; box-shadow: 0 0 3px #508ab2;
 margin:1px; font-size:12px; padding:0px 2px 0px 3px;" ></input>
    </div>
    <div class="PamphletWidget clearfix mse_pre_init" id="pamphletu6096"><!-- none box -->
     <div class="popup_anchor" id="u6097popup">
      <div class="ContainerGroup clearfix" id="u6097"><!-- stack box -->
       <div class="Container invi clearfix grpelem" id="u6098"><!-- column -->
        <div class="clearfix colelem" id="u6129-4"><!-- content -->
         <p>Ajuda?</p>
        </div>
        <div class="clearfix colelem" id="u6132-4"><!-- content -->
         <p>Esqueci a minha senha.</p>
        </div>
        <div class="clearfix colelem" id="u6150-4"><!-- content -->
         <p>Criar uma conta.</p>
        </div>
        <div class="clearfix colelem" id="u6135-4"><!-- content -->
         <p>Problemas com autenticação.</p>
        </div>
        <div class="clearfix colelem" id="u6147-4"><!-- content -->
         <p>Enviar relatório de erro.</p>
        </div>
       </div>
      </div>
     </div>
     <div class="ThumbGroup clearfix grpelem" id="u6099"><!-- none box -->
      <div class="popup_anchor" id="u6100popup">
       <div class="Thumb popup_element" id="u6100"><!-- simple frame --></div>
      </div>
     </div>
    </div>
   </div>
   <div class="clearfix grpelem" id="pu2581"><!-- column -->
    <div class="colelem" id="u2581"><!-- simple frame --></div>
    <div class="colelem" id="u2582"><!-- simple frame --></div>
    <div class="colelem" id="u2601"><!-- simple frame --></div>
   </div>
   <div class="verticalspacer" data-offset-top="1719" data-content-above-spacer="1719" data-content-below-spacer="0"></div>
  </div>
  <!-- Other scripts -->
  <script type="text/javascript">
   // Decide weather to suppress missing file error or not based on preference setting
var suppressMissingFileError = false
</script>
  <script type="text/javascript">
   window.Muse.assets.check=function(d){if(!window.Muse.assets.checked){window.Muse.assets.checked=!0;var b={},c=function(a,b){if(window.getComputedStyle){var c=window.getComputedStyle(a,null);return c&&c.getPropertyValue(b)||c&&c[b]||""}if(document.documentElement.currentStyle)return(c=a.currentStyle)&&c[b]||a.style&&a.style[b]||"";return""},a=function(a){if(a.match(/^rgb/))return a=a.replace(/\s+/g,"").match(/([\d\,]+)/gi)[0].split(","),(parseInt(a[0])<<16)+(parseInt(a[1])<<8)+parseInt(a[2]);if(a.match(/^\#/))return parseInt(a.substr(1),
16);return 0},g=function(g){for(var f=document.getElementsByTagName("link"),h=0;h<f.length;h++)if("text/css"==f[h].type){var i=(f[h].href||"").match(/\/?css\/([\w\-]+\.css)\?crc=(\d+)/);if(!i||!i[1]||!i[2])break;b[i[1]]=i[2]}f=document.createElement("div");f.className="version";f.style.cssText="display:none; width:1px; height:1px;";document.getElementsByTagName("body")[0].appendChild(f);for(h=0;h<Muse.assets.required.length;){var i=Muse.assets.required[h],l=i.match(/([\w\-\.]+)\.(\w+)$/),k=l&&l[1]?
l[1]:null,l=l&&l[2]?l[2]:null;switch(l.toLowerCase()){case "css":k=k.replace(/\W/gi,"_").replace(/^([^a-z])/gi,"_$1");f.className+=" "+k;k=a(c(f,"color"));l=a(c(f,"backgroundColor"));k!=0||l!=0?(Muse.assets.required.splice(h,1),"undefined"!=typeof b[i]&&(k!=b[i]>>>24||l!=(b[i]&16777215))&&Muse.assets.outOfDate.push(i)):h++;f.className="version";break;case "js":h++;break;default:throw Error("Unsupported file type: "+l);}}d?d().jquery!="1.8.3"&&Muse.assets.outOfDate.push("jquery-1.8.3.min.js"):Muse.assets.required.push("jquery-1.8.3.min.js");
f.parentNode.removeChild(f);if(Muse.assets.outOfDate.length||Muse.assets.required.length)f="Alguns arquivos no servidor podem estar ausentes ou incorretos. Limpe o cache do navegador e tente novamente. Se o problema persistir, entre em contato com o autor do site.",g&&Muse.assets.outOfDate.length&&(f+="\nOut of date: "+Muse.assets.outOfDate.join(",")),g&&Muse.assets.required.length&&(f+="\nMissing: "+Muse.assets.required.join(",")),suppressMissingFileError?(f+="\nUse SuppressMissingFileError key in AppPrefs.xml to show missing file error pop up.",console.log(f)):f};location&&location.search&&location.search.match&&location.search.match(/muse_debug/gi)?
setTimeout(function(){g(!0)},5E3):g()}};
var muse_init=function(){require.config({baseUrl:"https://portalget.com/src/"});require(["jquery","museutils","whatinput","jquery.watch","jquery.musepolyfill.bgsize","webpro","musewpslideshow","jquery.museoverlay","touchswipe","jquery.scrolleffects"],function(d){var $ = d;$(document).ready(function(){try{
window.Muse.assets.check($);/* body */
Muse.Utils.transformMarkupToFixBrowserProblemsPreInit();/* body */
Muse.Utils.prepHyperlinks(true);/* body */
Muse.Utils.resizeHeight('.browser_width');/* resize height */
Muse.Utils.requestAnimationFrame(function() { $('body').addClass('initialized'); });/* mark body as initialized */
Muse.Utils.makeButtonsVisibleAfterSettingMinWidth();/* body */
Muse.Utils.initWidget('#pamphletu6096', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_click',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:500,hideAllContentsFirst:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu6096 */
Muse.Utils.fullPage('#page');/* 100% height page */
$('#u2583').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,-49.97]},{"speed":[0,0],"in":[-49.97,Infinity]}]);/* scroll effect */
$('#u2584').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,0.03]},{"speed":[0,0],"in":[0.03,Infinity]}]);/* scroll effect */
$('#u2585').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,0.03]},{"speed":[0,0],"in":[0.03,Infinity]}]);/* scroll effect */
$('#u2595').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,0]},{"speed":[0,0],"in":[0,Infinity]}]);/* scroll effect */
$('#u2597-7').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,0.03]},{"speed":[0,0],"in":[0.03,Infinity]}]);/* scroll effect */
$('#u2598').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,0.03]},{"speed":[0,0],"in":[0.03,Infinity]}]);/* scroll effect */
$('#u2602-bw').registerPositionScrollEffect([{"speed":[null,1],"in":[-Infinity,-0.1]},{"speed":[null,0],"in":[-0.1,Infinity]}]);/* scroll effect */
$('#u2605').registerPositionScrollEffect([{"speed":[1,1],"in":[-Infinity,0]},{"speed":[0,0],"in":[0,Infinity]}]);/* scroll effect */
$('#u2606').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,0]},{"speed":[0,0],"in":[0,Infinity]}]);/* scroll effect */
$('#u2611').registerPositionScrollEffect([{"speed":[1,1],"in":[-Infinity,0]},{"speed":[0,0],"in":[0,Infinity]}]);/* scroll effect */
$('#u2586').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,0]},{"speed":[0,0],"in":[0,Infinity]}]);/* scroll effect */
$('#u2587').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,0]},{"speed":[0,0],"in":[0,Infinity]}]);/* scroll effect */
$('#u2588').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,0]},{"speed":[0,0],"in":[0,Infinity]}]);/* scroll effect */
$('#u2589').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,0]},{"speed":[0,0],"in":[0,Infinity]}]);/* scroll effect */
$('#u2590').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,0]},{"speed":[0,0],"in":[0,Infinity]}]);/* scroll effect */
$('#u2591').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,0]},{"speed":[0,0],"in":[0,Infinity]}]);/* scroll effect */
$('#u2689').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,-0.1]},{"speed":[0,0],"in":[-0.1,Infinity]}]);/* scroll effect */
$('#pamphletu6096').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,-0.1]},{"speed":[0,0],"in":[-0.1,Infinity]}]);/* scroll effect */
Muse.Utils.showWidgetsWhenReady();/* body */
Muse.Utils.transformMarkupToFixBrowserProblems();/* body */
}catch(b){if(b&&"function"==typeof b.notify?b.notify():Muse.Assert.fail("Error calling selector function: "+b),false)throw b;}})})};

</script>
  <!-- RequireJS script -->
  <script src="https://portalget.com/src/scripts/require.js?crc=4157109226" type="text/javascript" async data-main="https://portalget.com/src/scripts/museconfig.js?crc=4153641093" onload="if (requirejs) requirejs.onError = function(requireType, requireModule) { if (requireType && requireType.toString && requireType.toString().indexOf && 0 <= requireType.toString().indexOf('#scripterror')) window.Muse.assets.check(); }" onerror="window.Muse.assets.check();"></script>
   </body>
</html>
