<?php

?>

<!DOCTYPE html>
<html class="nojs html css_verticalspacer" lang="<?php echo $mcs->st_lang; ?>">
 <head>

  <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>
  <meta name="generator" content="2018.0.0.379"/>
  
  <script type="text/javascript">
   // Redirect to phone/tablet as necessary
(function(a,b,c){var d=function(){if(navigator.maxTouchPoints>1)return!0;if(window.matchMedia&&window.matchMedia("(-moz-touch-enabled)").matches)return!0;for(var a=["Webkit","Moz","O","ms","Khtml"],b=0,c=a.length;b<c;b++){var f=a[b]+"MaxTouchPoints";if(f in navigator&&navigator[f])return!0}try{return document.createEvent("TouchEvent"),!0}catch(d){}return!1}(),g=function(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var f=b[c];f.charAt(0)==" ";)f=f.substring(1,f.length);if(f.indexOf(a)==
0)return f.substring(a.length,f.length)}return null};if(g("inbrowserediting")!="true"){var f,g=g("devicelock");g=="phone"&&c?f=c:g=="tablet"&&b&&(f=b);if(g!=a&&!f)if(window.matchMedia)window.matchMedia("(max-device-width: 415px)").matches&&c?f=c:window.matchMedia("(max-device-width: 960px)").matches&&b&&d&&(f=b);else{var a=Math.min(screen.width,screen.height)/(window.devicePixelRatio||1),g=window.screen.systemXDPI||0,i=window.screen.systemYDPI||0,g=g>0&&i>0?Math.min(screen.width/g,screen.height/i):
0;(a<=370||g!=0&&g<=3)&&c?f=c:a<=960&&b&&d&&(f=b)}if(f)document.location=f+(document.location.search||"")+(document.location.hash||""),document.write('<style type="text/css">body {visibility:hidden}</style>')}})("desktop","","phone/index.html");

// Update the 'nojs'/'js' class on the html node
document.documentElement.className = document.documentElement.className.replace(/\bnojs\b/g, 'js');

// Check that all required assets are uploaded and up-to-date
if(typeof Muse == "undefined") window.Muse = {}; window.Muse.assets = {"required":["museutils.js", "museconfig.js", "jquery.watch.js", "require.js", "jquery.musepolyfill.bgsize.js", "webpro.js", "musewpslideshow.js", "jquery.museoverlay.js", "touchswipe.js", "jquery.musemenu.js", "jquery.scrolleffects.js", "index.css"], "outOfDate":[]};
</script>
  
  <link media="only screen and (max-width: 370px)" rel="alternate" href="https://www.portalget.com/phone/index.html"/>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" >
    <meta name="Description" content="<?php echo $mcs->st_title; ?>" />
    <meta name="<?php echo $mcs->st_autor; ?>" content="Portalget Inc">
    <title><?php echo $mcs->st_title; ?></title>
    <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/site_global.css?crc=444006867"/>
  <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/master_page-root.css?crc=3790829827"/>
  <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/index.css?crc=3768368494" id="pagesheet"/>
  <link rel="shortcut icon" href="<?php echo $mcs->st_favicon; ?>" type="image/x-icon"/>
   </head>
 <body>

  <div class="clearfix" id="page"><!-- group -->
   <div class="clearfix grpelem" id="pu17234"><!-- group -->

	<form action="/search/" method="get">
			<div id="u17234">
				<input type="text" class="lbl_ed_txt" name="q" ></input>
			</div>
			<div id="u17239"><!-- simple frame --></div>
			<div id="u17250"><!-- custom html -->
				<input type="submit" class="btn_seach_n1" value="Pesquisar">
			</div>
	</form>

    
    <div class="browser_width" id="u17124-bw">
     <div class="shadow" id="u17124"><!-- simple frame --></div>
    </div>
    <img class="museBGSize rounded-corners" id="u17128"  src="<?php echo $mcs->u_photo; ?>" >
    <div class="museBGSize" id="u17135"><!-- simple frame --></div>
    <div class="shadow rounded-corners" id="u17136"><!-- simple frame --></div>
    <div class="clearfix" id="u17137-4"><!-- content -->
     <p id="u17137-2">5</p>
    </div>
    <div class="PamphletWidget clearfix mse_pre_init" id="pamphletu24206"><!-- none box -->
     <div class="popup_anchor" id="u24215popup">
      <div class="ContainerGroup clearfix" id="u24215"><!-- stack box -->
       <div class="Container invi rounded-corners clearfix grpelem" id="u24216"><!-- column -->
        <div class="clearfix colelem" id="pu24280"><!-- group -->
         <div class="grpelem" id="u24280"><!-- simple frame --></div>
         <img class="museBGSize rounded-corners grpelem" src="<?php echo $mcs->u_photo; ?>" id="u24279" /> <!-- PROFILE IMAGE -->
         <div class="clearfix grpelem" id="u24217-4"><!-- content -->
          <p>agostinhopina95@gmail.com</p>
         </div>
         <div class="clearfix grpelem" id="u24241-4"><!-- content -->
          <p>Agostinho De Pina Ramos</p>
         </div>
        </div>
        <div class="clearfix colelem" id="u24242"><!-- column -->
         <nav class="MenuBar clearfix colelem" id="menuu24243"><!-- vertical box -->
          <div class="MenuItemContainer clearfix colelem" id="u24244"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24245"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u24247"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24246-4"><!-- content -->
             <p>Retroceder</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24265"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24266"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u24269"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24268-4"><!-- content -->
             <p>Editor Online</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24272"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24275"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u24278"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24276-4"><!-- content -->
             <p>Criar uma etiqueta</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24258"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24259"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u24261"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24260-4"><!-- content -->
             <p>Criar um grupo</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24251"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24254"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u24256"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24255-4"><!-- content -->
             <p>Ver questões</p>
            </div>
           </div>
          </div>
         </nav>
         <div class="colelem" id="u24218"><!-- simple frame --></div>
         <nav class="MenuBar clearfix colelem" id="menuu24219"><!-- vertical box -->
          <div class="MenuItemContainer clearfix colelem" id="u24227"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24230"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u24233"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24231-4"><!-- content -->
             <p>Definições</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24220"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24223"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u24226"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24225-4"><!-- content -->
             <p>Terminar sessão</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24234"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24235"><!-- horizontal box -->
            <div class="museBGSize grpelem" id="u24238"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24236-4"><!-- content -->
             <p>Ajuda</p>
            </div>
           </div>
          </div>
         </nav>
        </div>
       </div>
      </div>
     </div>
     <div class="ThumbGroup clearfix grpelem" id="u24213" ><!-- none box -->
      <div class="popup_anchor" id="u24214popup">
       <div class="Thumb popup_element" id="u24214"  src="<?php echo $mcs->u_photo; ?>" ><!-- simple frame --></div>
      </div>
     </div>
    </div>
    <div class="PamphletWidget clearfix mse_pre_init" id="pamphletu24281"><!-- none box -->
     <div class="popup_anchor" id="u24284popup">
      <div class="ContainerGroup clearfix" id="u24284"><!-- stack box -->
       <div class="Container invi rounded-corners clearfix grpelem" id="u24285"><!-- column -->
        <div class="clearfix colelem" id="pu24322"><!-- group -->
         <div class="rounded-corners grpelem" id="u24322"><!-- simple frame --></div>
         <div class="grpelem" id="u24288"><!-- simple frame --></div>
         <div class="museBGSize rounded-corners grpelem" id="u24321"><!-- content --></div>
         <div class="clearfix grpelem" id="u24290-6"><!-- content -->
          <p><span id="u24290">Agostinho de Pina Ramos</span> publicou em etiqueta <span id="u24290-3">Java.</span></p>
         </div>
         <div class="clearfix grpelem" id="u24289-4"><!-- content -->
          <p>Ontem ás 16h00</p>
         </div>
         <div class="museBGSize grpelem" id="u24320"><!-- simple frame --></div>
         <div class="grpelem" id="u24299"><!-- simple frame --></div>
         <div class="grpelem" id="u24293"><!-- simple frame --></div>
         <div class="museBGSize rounded-corners grpelem" id="u24296"><!-- content --></div>
         <div class="clearfix grpelem" id="u24291-6"><!-- content -->
          <p><span id="u24291">Agostinho de Pina Ramos</span> publicou em etiqueta <span id="u24291-3">Java.</span></p>
         </div>
         <div class="clearfix grpelem" id="u24292-4"><!-- content -->
          <p>Ontem ás 16h00</p>
         </div>
         <div class="museBGSize grpelem" id="u24300"><!-- simple frame --></div>
         <div class="grpelem" id="u24297"><!-- simple frame --></div>
         <div class="PamphletWidget clearfix grpelem" id="pamphletu24301"><!-- none box -->
          <div class="popup_anchor" id="u24310popup">
           <div class="ContainerGroup clearfix" id="u24310"><!-- stack box -->
            <div class="Container invi clearfix grpelem" id="u24311"><!-- group -->
             <div class="clearfix grpelem" id="pu24313"><!-- column -->
              <div class="colelem" id="u24313"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
              <div class="colelem" id="u24317"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
              <div class="colelem" id="u24312"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
              <div class="colelem" id="u24316"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
             </div>
             <div class="clearfix grpelem" id="pu24314-4"><!-- column -->
              <div class="clearfix colelem" id="u24314-4"><!-- content -->
               <p>Alert icon</p>
              </div>
              <div class="clearfix colelem" id="u24318-4"><!-- content -->
               <p>Alert song</p>
              </div>
              <div class="clearfix colelem" id="u24319-4"><!-- content -->
               <p>Auto refresh</p>
              </div>
              <div class="clearfix colelem" id="u24315-4"><!-- content -->
               <p>Desativar</p>
              </div>
             </div>
            </div>
           </div>
          </div>
          <div class="ThumbGroup clearfix grpelem" id="u24304"><!-- none box -->
           <div class="popup_anchor" id="u24305popup">
            <div class="Thumb popup_element museBGSize" id="u24305"><!-- simple frame --></div>
           </div>
          </div>
         </div>
         <div class="clearfix grpelem" id="u24294-4"><!-- content -->
          <p>Notificações</p>
         </div>
        </div>
        <div class="clearfix colelem" id="pu24295"><!-- group -->
         <div class="grpelem" id="u24295"><!-- simple frame --></div>
         <div class="museBGSize rounded-corners grpelem" id="u24287"><!-- content --></div>
         <div class="clearfix grpelem" id="u24324-6"><!-- content -->
          <p><span id="u24324">Agostinho de Pina Ramos</span> publicou em etiqueta <span id="u24324-3">Java.</span></p>
         </div>
         <div class="clearfix grpelem" id="u24298-4"><!-- content -->
          <p>Ontem ás 16h00</p>
         </div>
         <div class="museBGSize grpelem" id="u24323"><!-- simple frame --></div>
         <div class="grpelem" id="u24286"><!-- simple frame --></div>
        </div>
       </div>
      </div>
     </div>
     <div class="ThumbGroup clearfix grpelem" id="u24282"><!-- none box -->
      <div class="popup_anchor" id="u24283popup">
       <div class="Thumb popup_element" id="u24283"><!-- simple frame --></div>
      </div>
     </div>
    </div>
   </div>
   <div class="verticalspacer" data-offset-top="0" data-content-above-spacer="569" data-content-below-spacer="68"></div>
   <div class="browser_width grpelem" id="u17228-bw" >
    <div class="gradient" id="u17228" style="height:250px;"><!-- group -->
     <div class="clearfix" id="u17228_align_to_page" >
      <div class="clearfix grpelem" id="u17231-6" ><!-- content -->
       <p>Privacidade · Termos · Cookies · Português (Portugal) · mais</p>
       <p>Copyright 2017 © Portalget, Inc.</p>
      </div>
     </div>
    </div>
   </div>
  </div>
  <div class="preload_images">
   <img class="preload" src="images/icons8-bulleted-list-filled-50%20(1).png?crc=3853509856" alt=""/>
   <img class="preload" src="images/icons8-bulleted-list-filled-50.png?crc=3793801579" alt=""/>
   <img class="preload" src="images/icons8-price-tag-filled-50%20(1).png?crc=300400286" alt=""/>
   <img class="preload" src="images/icons8-price-tag-filled-50.png?crc=4163877127" alt=""/>
   <img class="preload" src="images/icons8-user-groups-filled-50%20(1).png?crc=387000346" alt=""/>
   <img class="preload" src="images/icons8-user-groups-filled-50.png?crc=448874755" alt=""/>
   <img class="preload" src="images/icons8-help-50%20(1).png?crc=320904700" alt=""/>
   <img class="preload" src="images/icons8-help-50.png?crc=3787903515" alt=""/>
   <img class="preload" src="images/icons8-settings-filled-50%20(1).png?crc=347087800" alt=""/>
   <img class="preload" src="images/icons8-settings-filled-50.png?crc=4116914146" alt=""/>
   <img class="preload" src="images/icons8-exit-filled-50%20(1).png?crc=269451593" alt=""/>
   <img class="preload" src="images/icons8-exit-filled-50.png?crc=523631758" alt=""/>
   <img class="preload" src="images/icons8-technical-support-24.png?crc=4293055341" alt=""/>
   <img class="preload" src="images/icons8-technical-support-24%20(1).png?crc=507442715" alt=""/>
  </div>
  <!-- Other scripts -->
  <script type="text/javascript">
   // Decide weather to suppress missing file error or not based on preference setting
var suppressMissingFileError = false
</script>
  <script type="text/javascript">
   window.Muse.assets.check=function(d){if(!window.Muse.assets.checked){window.Muse.assets.checked=!0;var b={},c=function(a,b){if(window.getComputedStyle){var c=window.getComputedStyle(a,null);return c&&c.getPropertyValue(b)||c&&c[b]||""}if(document.documentElement.currentStyle)return(c=a.currentStyle)&&c[b]||a.style&&a.style[b]||"";return""},a=function(a){if(a.match(/^rgb/))return a=a.replace(/\s+/g,"").match(/([\d\,]+)/gi)[0].split(","),(parseInt(a[0])<<16)+(parseInt(a[1])<<8)+parseInt(a[2]);if(a.match(/^\#/))return parseInt(a.substr(1),
16);return 0},g=function(g){for(var f=document.getElementsByTagName("link"),h=0;h<f.length;h++)if("text/css"==f[h].type){var i=(f[h].href||"").match(/\/?css\/([\w\-]+\.css)\?crc=(\d+)/);if(!i||!i[1]||!i[2])break;b[i[1]]=i[2]}f=document.createElement("div");f.className="version";f.style.cssText="display:none; width:1px; height:1px;";document.getElementsByTagName("body")[0].appendChild(f);for(h=0;h<Muse.assets.required.length;){var i=Muse.assets.required[h],l=i.match(/([\w\-\.]+)\.(\w+)$/),k=l&&l[1]?
l[1]:null,l=l&&l[2]?l[2]:null;switch(l.toLowerCase()){case "css":k=k.replace(/\W/gi,"_").replace(/^([^a-z])/gi,"_$1");f.className+=" "+k;k=a(c(f,"color"));l=a(c(f,"backgroundColor"));k!=0||l!=0?(Muse.assets.required.splice(h,1),"undefined"!=typeof b[i]&&(k!=b[i]>>>24||l!=(b[i]&16777215))&&Muse.assets.outOfDate.push(i)):h++;f.className="version";break;case "js":h++;break;default:throw Error("Unsupported file type: "+l);}}d?d().jquery!="1.8.3"&&Muse.assets.outOfDate.push("jquery-1.8.3.min.js"):Muse.assets.required.push("jquery-1.8.3.min.js");
f.parentNode.removeChild(f);if(Muse.assets.outOfDate.length||Muse.assets.required.length)f="Alguns arquivos no servidor podem estar ausentes ou incorretos. Limpe o cache do navegador e tente novamente. Se o problema persistir, entre em contato com o autor do site.",g&&Muse.assets.outOfDate.length&&(f+="\nOut of date: "+Muse.assets.outOfDate.join(",")),g&&Muse.assets.required.length&&(f+="\nMissing: "+Muse.assets.required.join(",")),suppressMissingFileError?(f+="\nUse SuppressMissingFileError key in AppPrefs.xml to show missing file error pop up.",console.log(f)):f};location&&location.search&&location.search.match&&location.search.match(/muse_debug/gi)?
setTimeout(function(){g(!0)},5E3):g()}};
var muse_init=function(){require.config({baseUrl:"https://portalget.com/src/"});require(["jquery","museutils","whatinput","jquery.musepolyfill.bgsize","jquery.musemenu","webpro","musewpslideshow","jquery.museoverlay","touchswipe","jquery.watch","jquery.scrolleffects"],function(d){var $ = d;$(document).ready(function(){try{
window.Muse.assets.check($);/* body */
Muse.Utils.transformMarkupToFixBrowserProblemsPreInit();/* body */
Muse.Utils.prepHyperlinks(true);/* body */
Muse.Utils.resizeHeight('.browser_width');/* resize height */
Muse.Utils.requestAnimationFrame(function() { $('body').addClass('initialized'); });/* mark body as initialized */
Muse.Utils.makeButtonsVisibleAfterSettingMinWidth();/* body */
Muse.Utils.initWidget('.MenuBar', ['#bp_infinity'], function(elem) { return $(elem).museMenu(); });/* unifiedNavBar */
Muse.Utils.initWidget('#pamphletu24206', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_both',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:0,hideAllContentsFirst:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu24206 */
Muse.Utils.initWidget('#pamphletu24301', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_click',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:0,hideAllContentsFirst:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu24301 */
Muse.Utils.initWidget('#pamphletu24281', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_both',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:0,hideAllContentsFirst:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu24281 */
Muse.Utils.fullPage('#page');/* 100% height page */
$('#pamphletu24206').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,-0.6]},{"speed":[0,0],"in":[-0.6,Infinity]}]);/* scroll effect */
$('#pamphletu24281').registerPositionScrollEffect([{"speed":[0,1],"in":[-Infinity,-0.6]},{"speed":[0,0],"in":[-0.6,Infinity]}]);/* scroll effect */
Muse.Utils.showWidgetsWhenReady();/* body */
Muse.Utils.transformMarkupToFixBrowserProblems();/* body */
}catch(b){if(b&&"function"==typeof b.notify?b.notify():Muse.Assert.fail("Error calling selector function: "+b),false)throw b;}})})};

</script>
  <!-- RequireJS script -->
  <script src="https://portalget.com/src/scripts/require.js?crc=4157109226" type="text/javascript" async data-main="https://portalget.com/src/scripts/museconfig.js?crc=4153641093" onload="if (requirejs) requirejs.onError = function(requireType, requireModule) { if (requireType && requireType.toString && requireType.toString().indexOf && 0 <= requireType.toString().indexOf('#scripterror')) window.Muse.assets.check(); }" onerror="window.Muse.assets.check();"></script>
   </body>
   
   <style>
   .btn_seach_n1{
		background: #508ab2;
		background-image: -webkit-linear-gradient(top, #508ab2, #2980b9);
		background-image: -moz-linear-gradient(top, #508ab2, #2980b9);
		background-image: -ms-linear-gradient(top, #508ab2, #2980b9);
		background-image: -o-linear-gradient(top, #508ab2, #2980b9);
		background-image: linear-gradient(to bottom, #508ab2, #2980b9);
		text-shadow: 1px 1px 3px #666666;
		-webkit-box-shadow: 0px 1px 3px #666666;
		-moz-box-shadow: 0px 1px 3px #666666;
		box-shadow: 0px 1px 3px #666666;
		font-family: Arial;
		color: #ffffff;
		font-size: 15px;
		padding: 10px 25px;
		background: #508ab2;
		text-decoration: none;
   }
   
   .lbl_ed_txt{
		width:510px; 
		height:40px; box-shadow: 0 0 3px #508ab2;
		margin:1px; font-size:14px; padding:0px 15px 0px 15px;
   }
   </style>
</html>
