<!DOCTYPE html>
<html class="nojs html css_verticalspacer" lang="pt-BR">
 <head>

  <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>
  <meta name="generator" content="2018.1.0.386"/>
  
  <script type="text/javascript">
   // Update the 'nojs'/'js' class on the html node
document.documentElement.className = document.documentElement.className.replace(/\bnojs\b/g, 'js');

// Check that all required assets are uploaded and up-to-date
if(typeof Muse == "undefined") window.Muse = {}; window.Muse.assets = {"required":["museutils.js", "museconfig.js", "jquery.watch.js", "require.js", "webpro.js", "musewpslideshow.js", "jquery.museoverlay.js", "touchswipe.js", "jquery.musemenu.js", "jquery.scrolleffects.js", "friends.css"], "outOfDate":[]};
</script>
  
  <title>friends</title>
  <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/site_global.css?crc=444006867"/>
  <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/master_page-root.css?crc=4014310853"/>
  <link rel="stylesheet" type="text/css" href="https://portalget.com/src/css/friends.css?crc=179403593" id="pagesheet"/>
  <!-- JS includes -->
  <!--[if lt IE 9]>
  <script src="scripts/html5shiv.js?crc=4241844378" type="text/javascript"></script>
  <![endif]-->
   </head>
 <body>

  <div class="clearfix" id="page"><!-- group -->
   <div class="clearfix grpelem" id="pu17124"><!-- group -->
    <div class="browser_width" id="u17124-bw">
     <div id="u17124"><!-- simple frame --></div>
    </div>
    <div id="u17128"><!-- simple frame --></div>
    <div id="u17135"><!-- simple frame --></div>
    <div id="u17136"><!-- simple frame --></div>
    <div class="clearfix" id="u17137-4"><!-- content -->
     <p id="u17137-2">5</p>
    </div>
    <div class="PamphletWidget clearfix mse_pre_init" id="pamphletu24206"><!-- none box -->
     <div class="popup_anchor" id="u24215popup">
      <div class="ContainerGroup clearfix" id="u24215"><!-- stack box -->
       <div class="Container invi clearfix grpelem" id="u24216"><!-- column -->
        <div class="clearfix colelem" id="pu24280"><!-- group -->
         <div class="grpelem" id="u24280"><!-- simple frame --></div>
         <div class="grpelem" id="u24279"><!-- simple frame --></div>
         <div class="clearfix grpelem" id="u24217-4"><!-- content -->
          <p>agostinhopina95@gmail.com</p>
         </div>
         <div class="clearfix grpelem" id="u24241-4"><!-- content -->
          <p>Agostinho De Pina Ramos</p>
         </div>
        </div>
        <div class="clearfix colelem" id="u24242"><!-- column -->
         <nav class="MenuBar clearfix colelem" id="menuu24243"><!-- vertical box -->
          <div class="MenuItemContainer clearfix colelem" id="u24244"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24245"><!-- horizontal box -->
            <div class="grpelem" id="u24247"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24246-4"><!-- content -->
             <p>Retroceder</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24265"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24266"><!-- horizontal box -->
            <div class="grpelem" id="u24269"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24268-4"><!-- content -->
             <p>Editor Online</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24272"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24275"><!-- horizontal box -->
            <div class="grpelem" id="u24278"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24276-4"><!-- content -->
             <p>Criar uma etiqueta</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24258"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24259"><!-- horizontal box -->
            <div class="grpelem" id="u24261"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24260-4"><!-- content -->
             <p>Criar um grupo</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24251"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24254"><!-- horizontal box -->
            <div class="grpelem" id="u24256"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24255-4"><!-- content -->
             <p>Ver questões</p>
            </div>
           </div>
          </div>
         </nav>
         <div class="colelem" id="u24218"><!-- simple frame --></div>
         <nav class="MenuBar clearfix colelem" id="menuu24219"><!-- vertical box -->
          <div class="MenuItemContainer clearfix colelem" id="u24227"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24230"><!-- horizontal box -->
            <div class="grpelem" id="u24233"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24231-4"><!-- content -->
             <p>Definições</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24220"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24223"><!-- horizontal box -->
            <div class="grpelem" id="u24226"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24225-4"><!-- content -->
             <p>Terminar sessão</p>
            </div>
           </div>
          </div>
          <div class="MenuItemContainer clearfix colelem" id="u24234"><!-- horizontal box -->
           <div class="MenuItem MenuItemWithSubMenu clearfix grpelem" id="u24235"><!-- horizontal box -->
            <div class="grpelem" id="u24238"><!-- content --></div>
            <div class="MenuItemLabel clearfix grpelem" id="u24236-4"><!-- content -->
             <p>Ajuda</p>
            </div>
           </div>
          </div>
         </nav>
        </div>
       </div>
      </div>
     </div>
     <div class="ThumbGroup clearfix grpelem" id="u24213"><!-- none box -->
      <div class="popup_anchor" id="u24214popup">
       <div class="Thumb popup_element" id="u24214"><!-- simple frame --></div>
      </div>
     </div>
    </div>
    <div class="PamphletWidget clearfix mse_pre_init" id="pamphletu24281"><!-- none box -->
     <div class="popup_anchor" id="u24284popup">
      <div class="ContainerGroup clearfix" id="u24284"><!-- stack box -->
       <div class="Container invi clearfix grpelem" id="u24285"><!-- column -->
        <div class="clearfix colelem" id="pu24322"><!-- group -->
         <div class="grpelem" id="u24322"><!-- simple frame --></div>
         <div class="grpelem" id="u24288"><!-- simple frame --></div>
         <div class="grpelem" id="u24321"><!-- content --></div>
         <div class="clearfix grpelem" id="u24290-6"><!-- content -->
          <p><span id="u24290">Agostinho de Pina Ramos</span> publicou em etiqueta <span id="u24290-3">Java.</span></p>
         </div>
         <div class="clearfix grpelem" id="u24289-4"><!-- content -->
          <p>Ontem ás 16h00</p>
         </div>
         <div class="grpelem" id="u24320"><!-- simple frame --></div>
         <div class="grpelem" id="u24299"><!-- simple frame --></div>
         <div class="grpelem" id="u24293"><!-- simple frame --></div>
         <div class="grpelem" id="u24296"><!-- content --></div>
         <div class="clearfix grpelem" id="u24291-6"><!-- content -->
          <p><span id="u24291">Agostinho de Pina Ramos</span> publicou em etiqueta <span id="u24291-3">Java.</span></p>
         </div>
         <div class="clearfix grpelem" id="u24292-4"><!-- content -->
          <p>Ontem ás 16h00</p>
         </div>
         <div class="grpelem" id="u24300"><!-- simple frame --></div>
         <div class="grpelem" id="u24297"><!-- simple frame --></div>
         <div class="PamphletWidget clearfix grpelem" id="pamphletu24301"><!-- none box -->
          <div class="popup_anchor" id="u24310popup">
           <div class="ContainerGroup clearfix" id="u24310"><!-- stack box -->
            <div class="Container invi clearfix grpelem" id="u24311"><!-- group -->
             <div class="clearfix grpelem" id="pu24313"><!-- column -->
              <div class="colelem" id="u24313"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
              <div class="colelem" id="u24317"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
              <div class="colelem" id="u24312"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
              <div class="colelem" id="u24316"><!-- custom html -->
               <input type="checkbox" value="" >
              </div>
             </div>
             <div class="clearfix grpelem" id="pu24314-4"><!-- column -->
              <div class="clearfix colelem" id="u24314-4"><!-- content -->
               <p>Alert icon</p>
              </div>
              <div class="clearfix colelem" id="u24318-4"><!-- content -->
               <p>Alert song</p>
              </div>
              <div class="clearfix colelem" id="u24319-4"><!-- content -->
               <p>Auto refresh</p>
              </div>
              <div class="clearfix colelem" id="u24315-4"><!-- content -->
               <p>Desativar</p>
              </div>
             </div>
            </div>
           </div>
          </div>
          <div class="ThumbGroup clearfix grpelem" id="u24304"><!-- none box -->
           <div class="popup_anchor" id="u24305popup">
            <div class="Thumb popup_element" id="u24305"><!-- simple frame --></div>
           </div>
          </div>
         </div>
         <div class="clearfix grpelem" id="u24294-4"><!-- content -->
          <p>Notificações</p>
         </div>
        </div>
        <div class="clearfix colelem" id="pu24295"><!-- group -->
         <div class="grpelem" id="u24295"><!-- simple frame --></div>
         <div class="grpelem" id="u24287"><!-- content --></div>
         <div class="clearfix grpelem" id="u24324-6"><!-- content -->
          <p><span id="u24324">Agostinho de Pina Ramos</span> publicou em etiqueta <span id="u24324-3">Java.</span></p>
         </div>
         <div class="clearfix grpelem" id="u24298-4"><!-- content -->
          <p>Ontem ás 16h00</p>
         </div>
         <div class="grpelem" id="u24323"><!-- simple frame --></div>
         <div class="grpelem" id="u24286"><!-- simple frame --></div>
        </div>
       </div>
      </div>
     </div>
     <div class="ThumbGroup clearfix grpelem" id="u24282"><!-- none box -->
      <div class="popup_anchor" id="u24283popup">
       <div class="Thumb popup_element" id="u24283"><!-- simple frame --></div>
      </div>
     </div>
    </div>
   </div>
   <div class="verticalspacer" data-offset-top="0" data-content-above-spacer="569" data-content-below-spacer="69"></div>
   <div class="browser_width grpelem" id="u17228-bw">
    <div id="u17228"><!-- group -->
     <div class="clearfix" id="u17228_align_to_page">
      <div class="clearfix grpelem" id="u17231-6"><!-- content -->
       <p>Privacidade · Termos · Cookies · Português (Portugal) · mais</p>
       <p>Copyright 2017 © Portalget, Inc.</p>
      </div>
     </div>
    </div>
   </div>
  </div>
  <!-- Other scripts -->
  <script type="text/javascript">
   // Decide whether to suppress missing file error or not based on preference setting
var suppressMissingFileError = false
</script>
  <script type="text/javascript">
   window.Muse.assets.check=function(c){if(!window.Muse.assets.checked){window.Muse.assets.checked=!0;var b={},d=function(a,b){if(window.getComputedStyle){var c=window.getComputedStyle(a,null);return c&&c.getPropertyValue(b)||c&&c[b]||""}if(document.documentElement.currentStyle)return(c=a.currentStyle)&&c[b]||a.style&&a.style[b]||"";return""},a=function(a){if(a.match(/^rgb/))return a=a.replace(/\s+/g,"").match(/([\d\,]+)/gi)[0].split(","),(parseInt(a[0])<<16)+(parseInt(a[1])<<8)+parseInt(a[2]);if(a.match(/^\#/))return parseInt(a.substr(1),
16);return 0},f=function(f){for(var g=document.getElementsByTagName("link"),j=0;j<g.length;j++)if("text/css"==g[j].type){var l=(g[j].href||"").match(/\/?css\/([\w\-]+\.css)\?crc=(\d+)/);if(!l||!l[1]||!l[2])break;b[l[1]]=l[2]}g=document.createElement("div");g.className="version";g.style.cssText="display:none; width:1px; height:1px;";document.getElementsByTagName("body")[0].appendChild(g);for(j=0;j<Muse.assets.required.length;){var l=Muse.assets.required[j],k=l.match(/([\w\-\.]+)\.(\w+)$/),i=k&&k[1]?
k[1]:null,k=k&&k[2]?k[2]:null;switch(k.toLowerCase()){case "css":i=i.replace(/\W/gi,"_").replace(/^([^a-z])/gi,"_$1");g.className+=" "+i;i=a(d(g,"color"));k=a(d(g,"backgroundColor"));i!=0||k!=0?(Muse.assets.required.splice(j,1),"undefined"!=typeof b[l]&&(i!=b[l]>>>24||k!=(b[l]&16777215))&&Muse.assets.outOfDate.push(l)):j++;g.className="version";break;case "js":j++;break;default:throw Error("Unsupported file type: "+k);}}c?c().jquery!="1.8.3"&&Muse.assets.outOfDate.push("jquery-1.8.3.min.js"):Muse.assets.required.push("jquery-1.8.3.min.js");
g.parentNode.removeChild(g);if(Muse.assets.outOfDate.length||Muse.assets.required.length)g="Alguns arquivos no servidor podem estar ausentes ou incorretos. Limpe o cache do navegador e tente novamente. Se o problema persistir, entre em contato com o autor do site.",f&&Muse.assets.outOfDate.length&&(g+="\nOut of date: "+Muse.assets.outOfDate.join(",")),f&&Muse.assets.required.length&&(g+="\nMissing: "+Muse.assets.required.join(",")),suppressMissingFileError?(g+="\nUse SuppressMissingFileError key in AppPrefs.xml to show missing file error pop up.",console.log(g)):g};location&&location.search&&location.search.match&&location.search.match(/muse_debug/gi)?
setTimeout(function(){f(!0)},5E3):f()}};
var muse_init=function(){require.config({baseUrl:"https://portalget.com/src/"});require(["jquery","museutils","whatinput","jquery.musemenu","webpro","musewpslideshow","jquery.museoverlay","touchswipe","jquery.watch","jquery.scrolleffects"],function(c){var $ = c;$(document).ready(function(){try{
window.Muse.assets.check($);/* body */
Muse.Utils.transformMarkupToFixBrowserProblemsPreInit();/* body */
Muse.Utils.prepHyperlinks(true);/* body */
Muse.Utils.resizeHeight('.browser_width');/* resize height */
Muse.Utils.requestAnimationFrame(function() { $('body').addClass('initialized'); });/* mark body as initialized */
Muse.Utils.makeButtonsVisibleAfterSettingMinWidth();/* body */
Muse.Utils.initWidget('.MenuBar', ['#bp_infinity'], function(elem) { return $(elem).museMenu(); });/* unifiedNavBar */
Muse.Utils.initWidget('#pamphletu24206', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_both',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:0,hideAllContentsFirst:true,triggersOnTop:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu24206 */
Muse.Utils.initWidget('#pamphletu24301', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_click',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:0,hideAllContentsFirst:true,triggersOnTop:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu24301 */
Muse.Utils.initWidget('#pamphletu24281', ['#bp_infinity'], function(elem) { return new WebPro.Widget.ContentSlideShow(elem, {contentLayout_runtime:'stack',event:'click',deactivationEvent:'mouseout_both',autoPlay:false,displayInterval:3000,transitionStyle:'fading',transitionDuration:0,hideAllContentsFirst:true,triggersOnTop:true,shuffle:false,enableSwipe:true,resumeAutoplay:true,resumeAutoplayInterval:3000,playOnce:false,autoActivate_runtime:false,isResponsive:false}); });/* #pamphletu24281 */
Muse.Utils.fullPage('#page');/* 100% height page */
$('#pamphletu24206').registerPositionScrollEffect([{"in":[-Infinity,-0.6],"speed":[0,1]},{"in":[-0.6,Infinity],"speed":[0,0]}]);/* scroll effect */
$('#pamphletu24281').registerPositionScrollEffect([{"in":[-Infinity,-0.6],"speed":[0,1]},{"in":[-0.6,Infinity],"speed":[0,0]}]);/* scroll effect */
Muse.Utils.showWidgetsWhenReady();/* body */
Muse.Utils.transformMarkupToFixBrowserProblems();/* body */
}catch(b){if(b&&"function"==typeof b.notify?b.notify():Muse.Assert.fail("Error calling selector function: "+b),false)throw b;}})})};

</script>
  <!-- RequireJS script -->
  <script src="https://portalget.com/src/scripts/require.js?crc=7928878" type="text/javascript" async data-main="https://portalget.com/src/scripts/museconfig.js?crc=310584261" onload="if (requirejs) requirejs.onError = function(requireType, requireModule) { if (requireType && requireType.toString && requireType.toString().indexOf && 0 <= requireType.toString().indexOf('#scripterror')) window.Muse.assets.check(); }" onerror="window.Muse.assets.check();"></script>
   </body>
</html>
